/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Flagright from "../../..";

export type BusinessSavedPaymentDetailsItem =
    | Flagright.BusinessSavedPaymentDetailsItem.Card
    | Flagright.BusinessSavedPaymentDetailsItem.GenericBankAccount
    | Flagright.BusinessSavedPaymentDetailsItem.Iban
    | Flagright.BusinessSavedPaymentDetailsItem.Ach
    | Flagright.BusinessSavedPaymentDetailsItem.Swift
    | Flagright.BusinessSavedPaymentDetailsItem.Mpesa
    | Flagright.BusinessSavedPaymentDetailsItem.Upi
    | Flagright.BusinessSavedPaymentDetailsItem.Wallet
    | Flagright.BusinessSavedPaymentDetailsItem.Check
    | Flagright.BusinessSavedPaymentDetailsItem.Cash;

export declare namespace BusinessSavedPaymentDetailsItem {
    interface Card extends Flagright.CardDetails {
        method: "CARD";
    }

    interface GenericBankAccount extends Flagright.GenericBankAccountDetails {
        method: "GENERIC_BANK_ACCOUNT";
    }

    interface Iban extends Flagright.IbanDetails {
        method: "IBAN";
    }

    interface Ach extends Flagright.AchDetails {
        method: "ACH";
    }

    interface Swift extends Flagright.SwiftDetails {
        method: "SWIFT";
    }

    interface Mpesa extends Flagright.MpesaDetails {
        method: "MPESA";
    }

    interface Upi extends Flagright.UpiDetails {
        method: "UPI";
    }

    interface Wallet extends Flagright.WalletDetails {
        method: "WALLET";
    }

    interface Check extends Flagright.CheckDetails {
        method: "CHECK";
    }

    interface Cash extends Flagright.CheckDetails {
        method: "CASH";
    }
}
