/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Flagright from "../../..";

export interface BusinessUsersCreateResponse extends Flagright.BusinessUserMonitoringResult {
    message?: string;
}
