/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Flagright from "../../../..";

export interface TransactionsVerifyRequest {
    /**
     * Boolean string whether Flagright should validate if provided originUserId exist. True by default
     */
    validateOriginUserId?: Flagright.BooleanString;
    /**
     * Boolean string whether Flagright should validate if provided destinationUserId exist. True by default
     */
    validateDestinationUserId?: Flagright.BooleanString;
    body: Flagright.Transaction;
}
