/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { FlagrightApi } from "@fern-api/flagright";

export interface CheckDetails {
    checkNumber?: string;
    checkIdentifier?: string;
    name?: string;
    deliveryStatus?: FlagrightApi.CheckDeliveryStatus;
    etaTimestamp?: number;
    shippingAddress?: FlagrightApi.Address;
}
