/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { FlagrightApi } from "@fern-api/flagright";

/**
 * Standardized model for a Generic wallet transaction
 */
export interface WalletDetails {
    walletType: string;
    walletId?: string;
    paymentChannel?: string;
    name?: string;
    tags?: FlagrightApi.Tag;
    walletPhoneNumber?: string;
}
