/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "../../../../environments";
import * as core from "../../../../core";
import { FlagrightApi } from "@fern-api/flagright";
import urlJoin from "url-join";
import * as serializers from "../../../../serialization";
import * as errors from "../../../../errors";

export declare namespace Client {
    interface Options {
        environment?: environments.FlagrightApiEnvironment | string;
        apiKey?: core.Supplier<string>;
    }
}

export class Client {
    constructor(private readonly options: Client.Options) {}

    public async create(request: FlagrightApi.User): Promise<FlagrightApi.CreateConsumerUsersResponse> {
        const _response = await core.fetcher({
            url: urlJoin(this.options.environment ?? environments.FlagrightApiEnvironment.Production, "consumer/users"),
            method: "POST",
            headers: {
                "X-API-KEY": await core.Supplier.get(this.options.apiKey),
            },
            body: await serializers.consumerUser.create.Request.json(request),
        });
        if (_response.ok) {
            return await serializers.consumerUser.create.Response.parse(
                _response.body as serializers.consumerUser.create.Response.Raw
            );
        }

        if (_response.error.reason === "status-code") {
            throw new errors.FlagrightApiError({
                statusCode: _response.error.statusCode,
                responseBody: _response.error.rawBody,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.FlagrightApiError({
                    statusCode: _response.error.statusCode,
                    responseBody: _response.error.rawBody,
                });
            case "timeout":
                throw new errors.FlagrightApiTimeoutError();
            case "unknown":
                throw new errors.FlagrightApiError({
                    message: _response.error.errorMessage,
                });
        }
    }

    public async retrieve(userId: string): Promise<FlagrightApi.User> {
        const _response = await core.fetcher({
            url: urlJoin(
                this.options.environment ?? environments.FlagrightApiEnvironment.Production,
                `consumer/users/${userId}`
            ),
            method: "GET",
            headers: {
                "X-API-KEY": await core.Supplier.get(this.options.apiKey),
            },
        });
        if (_response.ok) {
            return await serializers.consumerUser.retrieve.Response.parse(
                _response.body as serializers.consumerUser.retrieve.Response.Raw
            );
        }

        if (_response.error.reason === "status-code") {
            throw new errors.FlagrightApiError({
                statusCode: _response.error.statusCode,
                responseBody: _response.error.rawBody,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.FlagrightApiError({
                    statusCode: _response.error.statusCode,
                    responseBody: _response.error.rawBody,
                });
            case "timeout":
                throw new errors.FlagrightApiTimeoutError();
            case "unknown":
                throw new errors.FlagrightApiError({
                    message: _response.error.errorMessage,
                });
        }
    }

    public async createEvent(request: FlagrightApi.ConsumerUserEvent): Promise<FlagrightApi.User> {
        const _response = await core.fetcher({
            url: urlJoin(
                this.options.environment ?? environments.FlagrightApiEnvironment.Production,
                "events/consumer/user"
            ),
            method: "POST",
            headers: {
                "X-API-KEY": await core.Supplier.get(this.options.apiKey),
            },
            body: await serializers.consumerUser.createEvent.Request.json(request),
        });
        if (_response.ok) {
            return await serializers.consumerUser.createEvent.Response.parse(
                _response.body as serializers.consumerUser.createEvent.Response.Raw
            );
        }

        if (_response.error.reason === "status-code") {
            throw new errors.FlagrightApiError({
                statusCode: _response.error.statusCode,
                responseBody: _response.error.rawBody,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.FlagrightApiError({
                    statusCode: _response.error.statusCode,
                    responseBody: _response.error.rawBody,
                });
            case "timeout":
                throw new errors.FlagrightApiTimeoutError();
            case "unknown":
                throw new errors.FlagrightApiError({
                    message: _response.error.errorMessage,
                });
        }
    }
}
