/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { FlagrightApi } from "@fern-api/flagright";
import * as core from "../../../../core";

export const CardFunding: core.serialization.Schema<serializers.CardFunding.Raw, FlagrightApi.CardFunding> =
    core.serialization.enum_(["CREDIT", "DEBIT", "PREPAID"]);

export declare namespace CardFunding {
    type Raw = "CREDIT" | "DEBIT" | "PREPAID";
}
