/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { FlagrightApi } from "@fern-api/flagright";
import * as core from "../../../../core";

export const CheckDetails: core.serialization.ObjectSchema<serializers.CheckDetails.Raw, FlagrightApi.CheckDetails> =
    core.serialization.object({
        checkNumber: core.serialization.string().optional(),
        checkIdentifier: core.serialization.string().optional(),
        name: core.serialization.string().optional(),
        deliveryStatus: core.serialization.lazy(async () => (await import("../../..")).CheckDeliveryStatus).optional(),
        etaTimestamp: core.serialization.number().optional(),
        shippingAddress: core.serialization.lazyObject(async () => (await import("../../..")).Address).optional(),
    });

export declare namespace CheckDetails {
    interface Raw {
        checkNumber?: string | null;
        checkIdentifier?: string | null;
        name?: string | null;
        deliveryStatus?: serializers.CheckDeliveryStatus.Raw | null;
        etaTimestamp?: number | null;
        shippingAddress?: serializers.Address.Raw | null;
    }
}
