/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Flagright from "../../../../api";
import * as core from "../../../../core";

export const ConsumerUsersCreateResponse: core.serialization.ObjectSchema<
    serializers.ConsumerUsersCreateResponse.Raw,
    Flagright.ConsumerUsersCreateResponse
> = core.serialization
    .object({
        message: core.serialization.string().optional(),
    })
    .extend(core.serialization.lazyObject(async () => (await import("../../..")).ConsumerUserMonitoringResult));

export declare namespace ConsumerUsersCreateResponse {
    interface Raw extends serializers.ConsumerUserMonitoringResult.Raw {
        message?: string | null;
    }
}
