/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Flagright from "../index";

export interface AlertTagsUpdate {
    alertId?: string;
    /** Tags added, updated, or deleted on the alert. */
    tags?: Flagright.Tag[];
}
