/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Flagright from "../index";

export interface BatchTransactionEventMonitoringResult {
    transactionState: Flagright.TransactionState;
    /** Timestamp of the event */
    timestamp: number;
    /** Transaction ID the event pertains to */
    transactionId: string;
    /** Unique event ID */
    eventId?: string;
    /** Reason for the event or a state change */
    reason?: string;
    /** Event description */
    eventDescription?: string;
    updatedTransactionAttributes?: Flagright.TransactionUpdatable;
    metaData?: Flagright.DeviceData;
    /** External links related to the transaction */
    externalLinks?: string[];
    hitRules?: Flagright.HitRulesDetails[];
    status?: Flagright.RuleAction;
    riskScoreDetails?: Flagright.TransactionRiskScoringResult;
}
