/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Response from creation of a batch
 */
export interface BatchResponse {
    message?: string;
    batchId?: string;
    status?: string;
}
