/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Flagright from "../index";

export interface BatchTransactionMonitoringResults {
    transactions: Flagright.BatchTransactionMonitoringResult[];
    totalCount: number;
}
