/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Flagright from "../index";

/**
 * Response from creation of a batch
 */
export interface BatchResponse {
    status: Flagright.BatchResponseStatus;
    batchId: string;
    successful: number;
    failed: number;
    failedRecords?: Flagright.BatchResponseFailedRecord[];
    message?: string;
}
