/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Flagright from "../index";

export type BatchBusinessUserWithRulesResultSavedPaymentDetailsItem =
    | Flagright.BatchBusinessUserWithRulesResultSavedPaymentDetailsItem.Card
    | Flagright.BatchBusinessUserWithRulesResultSavedPaymentDetailsItem.GenericBankAccount
    | Flagright.BatchBusinessUserWithRulesResultSavedPaymentDetailsItem.Iban
    | Flagright.BatchBusinessUserWithRulesResultSavedPaymentDetailsItem.Ach
    | Flagright.BatchBusinessUserWithRulesResultSavedPaymentDetailsItem.Swift
    | Flagright.BatchBusinessUserWithRulesResultSavedPaymentDetailsItem.Mpesa
    | Flagright.BatchBusinessUserWithRulesResultSavedPaymentDetailsItem.Upi
    | Flagright.BatchBusinessUserWithRulesResultSavedPaymentDetailsItem.Wallet
    | Flagright.BatchBusinessUserWithRulesResultSavedPaymentDetailsItem.Check
    | Flagright.BatchBusinessUserWithRulesResultSavedPaymentDetailsItem.Cash
    | Flagright.BatchBusinessUserWithRulesResultSavedPaymentDetailsItem.Npp;

export namespace BatchBusinessUserWithRulesResultSavedPaymentDetailsItem {
    export interface Card extends Flagright.CardDetails {
        method: "CARD";
    }

    export interface GenericBankAccount extends Flagright.GenericBankAccountDetails {
        method: "GENERIC_BANK_ACCOUNT";
    }

    export interface Iban extends Flagright.IbanDetails {
        method: "IBAN";
    }

    export interface Ach extends Flagright.AchDetails {
        method: "ACH";
    }

    export interface Swift extends Flagright.SwiftDetails {
        method: "SWIFT";
    }

    export interface Mpesa extends Flagright.MpesaDetails {
        method: "MPESA";
    }

    export interface Upi extends Flagright.UpiDetails {
        method: "UPI";
    }

    export interface Wallet extends Flagright.WalletDetails {
        method: "WALLET";
    }

    export interface Check extends Flagright.CheckDetails {
        method: "CHECK";
    }

    export interface Cash extends Flagright.CashDetails {
        method: "CASH";
    }

    export interface Npp extends Flagright.NppDetails {
        method: "NPP";
    }
}
