/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type BlockchainRiskSubjectDirection = "ORIGIN" | "DESTINATION";
export const BlockchainRiskSubjectDirection = {
    Origin: "ORIGIN",
    Destination: "DESTINATION",
} as const;
