/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Flagright from "../index";

/**
 * Exposure information for a blockchain risk category
 */
export interface BlockchainRiskExposure {
    /** Amount exposed to this risk (fraction of transaction amount) */
    amount?: number;
    currency?: Flagright.CurrencyCode;
    /** Type of exposure (direct or indirect) */
    exposureType?: Flagright.RiskExposureType;
    /** Additional information that can be added via tags */
    tags?: Flagright.Tag[];
}
