/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Flagright from "../index";

/**
 * Detailed risk category analysis for a specific risk type
 */
export interface BlockchainRiskDetail {
    /** Optional alert identifier (alerts don't always exist) */
    alertId?: string;
    /** Unique identifier for the risk category */
    categoryId?: string;
    /** Human-readable name of the risk category */
    categoryName?: string;
    /** Risk level specific to this category */
    categoryRiskLevel?: Flagright.RiskLevel;
    /** Numeric risk score for this specific category */
    categoryRiskScore?: number;
    /** Type of exposure to the risk entity */
    exposureType?: Flagright.RiskExposureType;
    /** Name of the specific entity that poses the risk */
    entity?: string;
    /** Amount of the transaction exposed to this risk */
    exposureAmount?: Flagright.TransactionAmountDetails;
}
