/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Flagright from "../index";

/**
 * Detailed risk category analysis for a specific risk type
 */
export interface BlockchainRiskDetail {
    /** Optional alert identifier (alerts don't always exist) */
    alertId?: string;
    category?: Flagright.BlockchainRiskCategory;
    entity?: Flagright.BlockChainEntity;
    /** Exposure details for this risk category */
    exposure?: Flagright.BlockchainRiskExposure;
    /** Additional information that can be added via tags */
    tags?: Flagright.Tag[];
}
