/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Flagright from "../index";

/**
 * Model for a business user - optional fields
 */
export interface BusinessOptional {
    /** Timestamp when the user was activated */
    activatedTimestamp?: number;
    userStateDetails?: Flagright.UserStateDetails;
    kycStatusDetails?: Flagright.KycStatusDetails;
    eoddDate?: number;
    legalEntity?: Flagright.LegalEntity;
    /** Corporate entities of the user */
    corporateEntities?: Flagright.CorporateEntityDetails[];
    /** Shareholders (beneficiaries) of the company that hold at least 25% ownership. Can be another company or an individual */
    shareHolders?: Flagright.BusinessOptionalShareHoldersItem[];
    /** Director(s) of the company. Must be at least one */
    directors?: Flagright.Person[];
    /** Parties associated with the company. Can be another company or an individual */
    associatedParties?: Flagright.BusinessOptionalAssociatedPartiesItem[];
    /** Business partners of the company */
    businessPartners?: Flagright.LegalEntity[];
    transactionLimits?: Flagright.TransactionLimits;
    riskLevel?: Flagright.RiskLevel;
    kycRiskLevel?: Flagright.RiskLevel;
    allowedPaymentMethods?: Flagright.PaymentMethod[];
    /** Timestamp of the last successful transaction of the user */
    lastTransactionTimestamp?: number;
    linkedEntities?: Flagright.UserEntityLink;
    acquisitionChannel?: Flagright.AcquisitionChannel;
    savedPaymentDetails?: Flagright.BusinessOptionalSavedPaymentDetailsItem[];
    mccDetails?: Flagright.MccDetails;
    /** Additional information that can be added via tags */
    tags?: Flagright.UserTag[];
    /** User's attachments uploaded by business user */
    attachments?: Flagright.PersonAttachment[];
    metaData?: Flagright.DeviceData;
    /** Legal authority or region governing the transaction */
    jurisdiction?: string;
    updateCount?: number;
    productsEnabled?: Flagright.ProductsEnabled[];
    pepStatus?: Flagright.PepStatus[];
    /** Whether the user is sanctioned */
    sanctionsStatus?: boolean;
    /** Whether the user is in the adverse media list */
    adverseMediaStatus?: boolean;
}
