/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Flagright from "..";

/**
 * Model for a business user base fields
 */
export interface BusinessBase {
    /** Unique user ID for the user <span style="white-space: nowrap">`non-empty`</span> */
    userId: string;
    /** Timestamp when the user was created */
    createdTimestamp: number;
    legalEntity: Flagright.LegalEntity;
}
