/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Flagright from "../index";

export type BusinessSavedPaymentDetailsItem =
    | Flagright.BusinessSavedPaymentDetailsItem.Card
    | Flagright.BusinessSavedPaymentDetailsItem.GenericBankAccount
    | Flagright.BusinessSavedPaymentDetailsItem.Iban
    | Flagright.BusinessSavedPaymentDetailsItem.Ach
    | Flagright.BusinessSavedPaymentDetailsItem.Swift
    | Flagright.BusinessSavedPaymentDetailsItem.Mpesa
    | Flagright.BusinessSavedPaymentDetailsItem.Upi
    | Flagright.BusinessSavedPaymentDetailsItem.Wallet
    | Flagright.BusinessSavedPaymentDetailsItem.Check
    | Flagright.BusinessSavedPaymentDetailsItem.Cash;

export namespace BusinessSavedPaymentDetailsItem {
    export interface Card extends Flagright.CardDetails {
        method: "CARD";
    }

    export interface GenericBankAccount extends Flagright.GenericBankAccountDetails {
        method: "GENERIC_BANK_ACCOUNT";
    }

    export interface Iban extends Flagright.IbanDetails {
        method: "IBAN";
    }

    export interface Ach extends Flagright.AchDetails {
        method: "ACH";
    }

    export interface Swift extends Flagright.SwiftDetails {
        method: "SWIFT";
    }

    export interface Mpesa extends Flagright.MpesaDetails {
        method: "MPESA";
    }

    export interface Upi extends Flagright.UpiDetails {
        method: "UPI";
    }

    export interface Wallet extends Flagright.WalletDetails {
        method: "WALLET";
    }

    export interface Check extends Flagright.CheckDetails {
        method: "CHECK";
    }

    export interface Cash extends Flagright.CashDetails {
        method: "CASH";
    }
}
