/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Flagright from "../index";

export interface BusinessWithRulesResult {
    /** Unique user ID for the user */
    userId: string;
    /** Timestamp when the user was created */
    createdTimestamp: number;
    legalEntity: Flagright.LegalEntity;
    /** Timestamp when the user was activated */
    activatedTimestamp?: number;
    userStateDetails?: Flagright.UserStateDetails;
    kycStatusDetails?: Flagright.KycStatusDetails;
    eoddDate?: number;
    /** Corporate entities of the user */
    corporateEntities?: Flagright.CorporateEntityDetails[];
    /** Shareholders (beneficiaries) of the company that hold at least 25% ownership. Can be another company or an individual */
    shareHolders?: Flagright.BusinessWithRulesResultShareHoldersItem[];
    /** Director(s) of the company. Must be at least one */
    directors?: Flagright.BusinessWithRulesResultDirectorsItem[];
    /** Parties associated with the company. Can be another company or an individual */
    associatedParties?: Flagright.BusinessWithRulesResultAssociatedPartiesItem[];
    /** Business partners of the company */
    businessPartners?: Flagright.LegalEntity[];
    transactionLimits?: Flagright.TransactionLimits;
    expectedTransactionCountries?: Flagright.ExpectedTransactionCountries;
    riskLevel?: Flagright.RiskLevel;
    kycRiskLevel?: Flagright.RiskLevel;
    allowedPaymentMethods?: Flagright.PaymentMethod[];
    linkedEntities?: Flagright.UserEntityLink;
    acquisitionChannel?: Flagright.AcquisitionChannel;
    savedPaymentDetails?: Flagright.BusinessWithRulesResultSavedPaymentDetailsItem[];
    mccDetails?: Flagright.MccDetails;
    /** Additional information that can be added via tags */
    tags?: Flagright.UserTag[];
    /** User's attachments uploaded by business user */
    attachments?: Flagright.PersonAttachment[];
    metaData?: Flagright.DeviceData;
    /** Legal authority or region governing the transaction */
    jurisdiction?: string;
    productsEnabled?: Flagright.ProductsEnabled[];
    pepStatus?: Flagright.PepStatus[];
    /** Whether the user is sanctioned */
    sanctionsStatus?: boolean;
    /** Whether the user is in the adverse media list */
    adverseMediaStatus?: boolean;
    executedRules?: Flagright.ExecutedRulesResult[];
    hitRules?: Flagright.HitRulesDetails[];
    riskScoreDetails?: Flagright.UserRiskScoreDetails;
}
