/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type BusinessUserSegment = "SOLE_PROPRIETORSHIP" | "LIMITED" | "SMB" | "SMALL" | "MEDIUM" | "LARGE" | "UNKNOWN";

export const BusinessUserSegment = {
    SoleProprietorship: "SOLE_PROPRIETORSHIP",
    Limited: "LIMITED",
    Smb: "SMB",
    Small: "SMALL",
    Medium: "MEDIUM",
    Large: "LARGE",
    Unknown: "UNKNOWN",
} as const;
