/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Flagright from "..";

/**
 * Model for business payload with rules result
 */
export interface BusinessWithRulesResult extends Flagright.Business {
    executedRules?: Flagright.ExecutedRulesResult[];
    hitRules?: Flagright.HitRulesDetails[];
    riskScoreDetails?: Flagright.UserRiskScoreDetails;
}
