/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type CardDetailsCardType = "VIRTUAL" | "PHYSICAL";

export const CardDetailsCardType = {
    Virtual: "VIRTUAL",
    Physical: "PHYSICAL",
} as const;
