/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Funding of Card
 */
export type CardDetailsCardFunding = "CREDIT" | "DEBIT" | "PREPAID";

export const CardDetailsCardFunding = {
    Credit: "CREDIT",
    Debit: "DEBIT",
    Prepaid: "PREPAID",
} as const;
