/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type CaseCreationType = "TRANSACTION" | "USER";

export const CaseCreationType = {
    Transaction: "TRANSACTION",
    User: "USER",
} as const;
