/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Flagright from "../index";

export interface CaseStatusDetails {
    caseId?: string;
    caseType?: Flagright.CaseType;
    status?: string;
    reasons?: string[];
    reasonDescriptionForOther?: string;
    comment?: string;
    userId?: string;
    transactionIds?: string[];
    /** Id of the case group this case belongs to. Absent when the case is not mapped to a case group. */
    caseGroupId?: string;
    /** Display name of the case group. */
    caseGroupName?: string;
}
