/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface CaseOpenedDetails {
    caseId?: string;
    status?: string;
    userId?: string;
    transactionIds?: string[];
}
