/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Model for a generic consumer name
 */
export interface ConsumerName {
    /** First name of the user <span style="white-space: nowrap">`non-empty`</span> */
    firstName: string;
    /** Middle name of the user <span style="white-space: nowrap">`non-empty`</span> */
    middleName?: string;
    /** Last name of the user <span style="white-space: nowrap">`non-empty`</span> */
    lastName?: string;
}
