/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * KRS breakdown row from factor score details or component scores when available
 */
export interface CraRiskLevelUpdatedRiskFactor {
    riskFactorId?: string;
    /** Set for KRS factor score detail rows */
    riskFactorVersionId?: string;
    value?: string;
    riskScore?: number;
    riskLevel?: string;
    weight?: number;
}
