/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type EmploymentStatus =
    | "UNEMPLOYED"
    | "STUDENT"
    | "FULL_TIME"
    | "PART_TIME"
    | "SOLE_PROPRIETOR"
    | "PENSIONER"
    | "COMPANY_OWNER";

export const EmploymentStatus = {
    Unemployed: "UNEMPLOYED",
    Student: "STUDENT",
    FullTime: "FULL_TIME",
    PartTime: "PART_TIME",
    SoleProprietor: "SOLE_PROPRIETOR",
    Pensioner: "PENSIONER",
    CompanyOwner: "COMPANY_OWNER",
} as const;
