/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type EmploymentStatus =
    | "UNEMPLOYED"
    | "EMPLOYED"
    | "SELF_EMPLOYED"
    | "FREELANCER"
    | "STUDENT"
    | "FULL_TIME"
    | "PART_TIME"
    | "SOLE_PROPRIETOR"
    | "PENSIONER"
    | "COMPANY_OWNER"
    | "OTHER"
    | "NA";

export const EmploymentStatus = {
    Unemployed: "UNEMPLOYED",
    Employed: "EMPLOYED",
    SelfEmployed: "SELF_EMPLOYED",
    Freelancer: "FREELANCER",
    Student: "STUDENT",
    FullTime: "FULL_TIME",
    PartTime: "PART_TIME",
    SoleProprietor: "SOLE_PROPRIETOR",
    Pensioner: "PENSIONER",
    CompanyOwner: "COMPANY_OWNER",
    Other: "OTHER",
    Na: "NA",
} as const;
