/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Flagright from "../index";

/**
 * Model for list of executed rules
 */
export interface ExecutedRulesResult {
    /** Unique rule identifier */
    ruleId?: string;
    ruleInstanceId: string;
    /** Name of the rule */
    ruleName: string;
    /** Description of the rule */
    ruleDescription: string;
    ruleAction: Flagright.RuleAction;
    ruleHit: boolean;
    /** Timestamp when the rule was executed */
    executedAt?: number;
    ruleHitMeta?: Flagright.RuleHitMeta;
    vars?: Flagright.ExecutedLogicVars[];
    labels?: Flagright.RuleLabels[];
    nature?: Flagright.RuleNature;
    isShadow?: boolean;
    sanctionsDetails?: Flagright.RuleExecutionSanctionsDetails[];
}
