/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Flagright from "../index";

export interface ExecutedLogicVars {
    direction?: Flagright.RuleHitDirection;
    value: Record<string, unknown>;
}
