/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Flagright from "../index";

/**
 * Model for list of rules failed execution. It means rules could not be run
 */
export interface FailedRulesResult {
    /** Unique rule identifier */
    ruleId: string;
    /** Name of the rule */
    ruleName: string;
    /** Description of the rule */
    ruleDescription: string;
    failureException: Flagright.RuleFailureException;
}
