/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface FileInfo {
    s3Key: string;
    bucket?: string;
    filename: string;
    size: number;
    downloadLink?: string;
    aiSummary?: string;
}
