/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Flagright } from "flagright";

export interface KycStatusDetails {
    reason?: string;
    status?: Flagright.KycStatus;
}
