/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ListMetadata {
    /** List name */
    name?: string;
    /** List description */
    description?: string;
    status?: boolean;
    checksum?: string;
}
