/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface MccDetails {
    /** Merchant code */
    code: number;
    /** Merchant Description */
    description?: string;
}
