/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Flagright from "../index";

/**
 * New Payment Platform Details for Australia
 */
export interface NppDetails {
    /** Account number */
    accountNumber?: string;
    name?: Flagright.ConsumerName;
    emailId?: Flagright.EmailId;
    /** Contact number */
    contactNumber?: string;
    /** BSB number */
    bsb?: string;
    /** PayID */
    payId: string;
    /** End to End ID */
    endToEndId: string;
    /** OSKO reference */
    oskoReference?: string;
    /** PayID reference */
    payIdReference?: string;
    /** Whether the payment is instant */
    isInstant?: boolean;
    /** Remittance information */
    remittanceInformation?: string;
    /** Remittance advice */
    remittanceAdvice?: string;
    /** Additional information that can be added via tags */
    tags?: Flagright.Tag[];
    /** Timestamp of the event */
    processingDate?: number;
    /** Timestamp of the event */
    settlementDate?: number;
    /** Unique reference number for transaction reconciliation */
    referenceNumber?: string;
    /** Trace number for tracking the payment through the NPP system */
    traceNumber?: string;
    /** Format of the NPP message (e.g., JSON, XML) */
    messageFormat?: string;
    /** Name of the bank associated with the account */
    bankName?: string;
    address?: Flagright.Address;
}
