/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Classify the method of payment as "NPP" for NPPDetails (New Payment Platform Details for Australia)
 */
export type NppPaymentMethod = "NPP";
