/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type PaymentMethod =
    | "ACH"
    | "CARD"
    | "IBAN"
    | "UPI"
    | "GENERIC_BANK_ACCOUNT"
    | "MPESA"
    | "SWIFT"
    | "WALLET"
    | "CHECK";

export const PaymentMethod = {
    Ach: "ACH",
    Card: "CARD",
    Iban: "IBAN",
    Upi: "UPI",
    GenericBankAccount: "GENERIC_BANK_ACCOUNT",
    Mpesa: "MPESA",
    Swift: "SWIFT",
    Wallet: "WALLET",
    Check: "CHECK",
} as const;
