/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Flagright from "..";

/**
 * Model for a generic individual - different from User model by not having userId field
 */
export interface Person {
    generalDetails: Flagright.UserDetails;
    /** User's legal identity documents - See Document Model for details */
    legalDocuments?: Flagright.LegalDocument[];
    contactDetails?: Flagright.ContactDetails;
    pepStatus?: Flagright.PepStatus[];
    /** Additional information that can be added via tags */
    tags?: Flagright.Tag[];
}
