/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Flagright from "..";

/**
 * Place of birth of the individual
 */
export interface PlaceOfBirth {
    city?: string;
    state?: string;
    country: Flagright.CountryCode;
}
