/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Model for results from Risk Scoring
 */
export interface RiskScoringResult {
    /** Quantified KYC risk score */
    kycRiskScore: number;
    /** Quantified action risk score */
    actionRiskScore: number;
    /** Quantified dynamic risk score */
    dynamicRiskScore?: number;
}
