/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface RuleFailureException {
    /** Unique rule identifier */
    exceptionName: string;
    /** Name of the rule */
    exceptionDescription: string;
}
