/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Flagright from "../index";

export interface SanctionsHitContext {
    entity: Flagright.SanctionsScreeningEntity;
    entityType?: Flagright.SanctionsDetailsEntityType;
    userId?: string;
    transactionId?: string;
    ruleInstanceId?: string;
    ruleId?: string;
    iban?: string;
    yearOfBirth?: number;
    searchTerm?: string;
    paymentMethodId?: string;
}
