/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Attachment included with an inbound SAR message
 */
export interface SarMessageAttachment {
    fileName: string;
    /** Time-limited URL to download the attachment */
    url?: string;
    contentType?: string;
}
