/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Flagright from "../index";

/**
 * Payload sent for SAR lifecycle webhook events (SAR_CREATED, SAR_SUBMITTED, SAR_SUBMISSION_ACCEPTED).
 */
export interface SarWebhookDetails {
    /** Unique identifier of the SAR report */
    reportId: string;
    status: Flagright.SarReportStatus;
    /** ID of the subject user the SAR is filed against, if any */
    userId?: string;
    /** ID of the case the SAR is associated with, if any */
    caseId?: string;
    /** Timestamp at which the SAR was created. Measured in ms since the Unix epoch. */
    createdAt?: number;
}
