/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type SourceOfFunds =
    | "Earnings"
    | "Savings"
    | "Investments/Deposits"
    | "Wealth"
    | "Gift"
    | "Pension"
    | "Inheritance"
    | "Gambling"
    | "Benefits"
    | "Passive"
    | "Family"
    | "Insurance"
    | "Legal"
    | "Sales"
    | "Rollover"
    | "Equity"
    | "Crypto"
    | "Business"
    | "Employment";

export const SourceOfFunds = {
    Earnings: "Earnings",
    Savings: "Savings",
    InvestmentsDeposits: "Investments/Deposits",
    Wealth: "Wealth",
    Gift: "Gift",
    Pension: "Pension",
    Inheritance: "Inheritance",
    Gambling: "Gambling",
    Benefits: "Benefits",
    Passive: "Passive",
    Family: "Family",
    Insurance: "Insurance",
    Legal: "Legal",
    Sales: "Sales",
    Rollover: "Rollover",
    Equity: "Equity",
    Crypto: "Crypto",
    Business: "Business",
    Employment: "Employment",
} as const;
