/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type SourceOfFunds = "Earnings" | "Savings" | "Investments/Deposits" | "Wealth" | "Gift" | "Pension";

export const SourceOfFunds = {
    Earnings: "Earnings",
    Savings: "Savings",
    InvestmentsDeposits: "Investments/Deposits",
    Wealth: "Wealth",
    Gift: "Gift",
    Pension: "Pension",
} as const;
