/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Flagright from "../index";

/**
 * Additional metadata for transactions including risk analysis and counterparty information
 */
export interface TransactionMetadata {
    /** List of blockchain risk analyses from different providers */
    blockchainRisk?: Flagright.BlockchainRisk[];
}
