/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Flagright from "../index";

/**
 * Payment details of the origin. It can be a bank account number, wallet ID, card fingerprint etc.
 */
export type TransactionUpdatableOriginPaymentDetails =
    | Flagright.TransactionUpdatableOriginPaymentDetails.Card
    | Flagright.TransactionUpdatableOriginPaymentDetails.GenericBankAccount
    | Flagright.TransactionUpdatableOriginPaymentDetails.Iban
    | Flagright.TransactionUpdatableOriginPaymentDetails.Ach
    | Flagright.TransactionUpdatableOriginPaymentDetails.Swift
    | Flagright.TransactionUpdatableOriginPaymentDetails.Mpesa
    | Flagright.TransactionUpdatableOriginPaymentDetails.Upi
    | Flagright.TransactionUpdatableOriginPaymentDetails.Wallet
    | Flagright.TransactionUpdatableOriginPaymentDetails.Check
    | Flagright.TransactionUpdatableOriginPaymentDetails.Cash
    | Flagright.TransactionUpdatableOriginPaymentDetails.Npp;

export namespace TransactionUpdatableOriginPaymentDetails {
    export interface Card extends Flagright.CardDetails {
        method: "CARD";
    }

    export interface GenericBankAccount extends Flagright.GenericBankAccountDetails {
        method: "GENERIC_BANK_ACCOUNT";
    }

    export interface Iban extends Flagright.IbanDetails {
        method: "IBAN";
    }

    export interface Ach extends Flagright.AchDetails {
        method: "ACH";
    }

    export interface Swift extends Flagright.SwiftDetails {
        method: "SWIFT";
    }

    export interface Mpesa extends Flagright.MpesaDetails {
        method: "MPESA";
    }

    export interface Upi extends Flagright.UpiDetails {
        method: "UPI";
    }

    export interface Wallet extends Flagright.WalletDetails {
        method: "WALLET";
    }

    export interface Check extends Flagright.CheckDetails {
        method: "CHECK";
    }

    export interface Cash extends Flagright.CashDetails {
        method: "CASH";
    }

    export interface Npp extends Flagright.NppDetails {
        method: "NPP";
    }
}
