/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Flagright from "..";

export interface TransactionMonitoringResult extends Flagright.RulesResults {
    /** Transaction ID that the results pertain to */
    transactionId: string;
    status: Flagright.RuleAction;
    riskScoreDetails?: Flagright.TransactionRiskScoringResult;
}
