/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Flagright from "../index";

export type TransactionUpdatableDestinationPaymentDetails =
    | Flagright.TransactionUpdatableDestinationPaymentDetails.Card
    | Flagright.TransactionUpdatableDestinationPaymentDetails.GenericBankAccount
    | Flagright.TransactionUpdatableDestinationPaymentDetails.Iban
    | Flagright.TransactionUpdatableDestinationPaymentDetails.Ach
    | Flagright.TransactionUpdatableDestinationPaymentDetails.Upi
    | Flagright.TransactionUpdatableDestinationPaymentDetails.Wallet
    | Flagright.TransactionUpdatableDestinationPaymentDetails.Swift
    | Flagright.TransactionUpdatableDestinationPaymentDetails.Mpesa
    | Flagright.TransactionUpdatableDestinationPaymentDetails.Check
    | Flagright.TransactionUpdatableDestinationPaymentDetails.Cash;

export namespace TransactionUpdatableDestinationPaymentDetails {
    export interface Card extends Flagright.CardDetails {
        method: "CARD";
    }

    export interface GenericBankAccount extends Flagright.GenericBankAccountDetails {
        method: "GENERIC_BANK_ACCOUNT";
    }

    export interface Iban extends Flagright.IbanDetails {
        method: "IBAN";
    }

    export interface Ach extends Flagright.AchDetails {
        method: "ACH";
    }

    export interface Upi extends Flagright.UpiDetails {
        method: "UPI";
    }

    export interface Wallet extends Flagright.WalletDetails {
        method: "WALLET";
    }

    export interface Swift extends Flagright.SwiftDetails {
        method: "SWIFT";
    }

    export interface Mpesa extends Flagright.MpesaDetails {
        method: "MPESA";
    }

    export interface Check extends Flagright.CheckDetails {
        method: "CHECK";
    }

    export interface Cash extends Flagright.CashDetails {
        method: "CASH";
    }
}
