/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Flagright } from "@fern-api/flagright";

export interface TransactionLimit {
    transactionCountLimit?: Flagright.TransactionCountLimit;
    transactionAmountLimit?: Flagright.TransactionAmountLimit;
    averageTransactionAmountLimit?: Flagright.TransactionAmountLimit;
}
