/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Flagright from "../index";

/**
 * Payment details of the origin. It can be a bank account number, wallet ID, card fingerprint etc.
 */
export type TransactionWithRulesResultOriginPaymentDetails =
    | Flagright.TransactionWithRulesResultOriginPaymentDetails.Card
    | Flagright.TransactionWithRulesResultOriginPaymentDetails.GenericBankAccount
    | Flagright.TransactionWithRulesResultOriginPaymentDetails.Iban
    | Flagright.TransactionWithRulesResultOriginPaymentDetails.Ach
    | Flagright.TransactionWithRulesResultOriginPaymentDetails.Swift
    | Flagright.TransactionWithRulesResultOriginPaymentDetails.Mpesa
    | Flagright.TransactionWithRulesResultOriginPaymentDetails.Upi
    | Flagright.TransactionWithRulesResultOriginPaymentDetails.Wallet
    | Flagright.TransactionWithRulesResultOriginPaymentDetails.Check
    | Flagright.TransactionWithRulesResultOriginPaymentDetails.Cash;

export namespace TransactionWithRulesResultOriginPaymentDetails {
    export interface Card extends Flagright.CardDetails {
        method: "CARD";
    }

    export interface GenericBankAccount extends Flagright.GenericBankAccountDetails {
        method: "GENERIC_BANK_ACCOUNT";
    }

    export interface Iban extends Flagright.IbanDetails {
        method: "IBAN";
    }

    export interface Ach extends Flagright.AchDetails {
        method: "ACH";
    }

    export interface Swift extends Flagright.SwiftDetails {
        method: "SWIFT";
    }

    export interface Mpesa extends Flagright.MpesaDetails {
        method: "MPESA";
    }

    export interface Upi extends Flagright.UpiDetails {
        method: "UPI";
    }

    export interface Wallet extends Flagright.WalletDetails {
        method: "WALLET";
    }

    export interface Check extends Flagright.CheckDetails {
        method: "CHECK";
    }

    export interface Cash extends Flagright.CashDetails {
        method: "CASH";
    }
}
