/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type TransactionType = "DEPOSIT" | "TRANSFER" | "EXTERNAL_PAYMENT" | "WITHDRAWAL" | "REFUND";

export const TransactionType = {
    Deposit: "DEPOSIT",
    Transfer: "TRANSFER",
    ExternalPayment: "EXTERNAL_PAYMENT",
    Withdrawal: "WITHDRAWAL",
    Refund: "REFUND",
} as const;
