/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Flagright from "../index";

/**
 * Model for UPI payment method
 */
export interface UpiDetails {
    counterpartyType?: Flagright.CounterpartyType;
    /** UPI Id number */
    upiId: string;
    /** Bank provider name */
    bankProvider?: string;
    /** Interface provider name */
    interfaceProvider?: string;
    /** Name of the account holder */
    name?: string;
    address?: Flagright.Address;
    emailId?: Flagright.EmailId;
    /** Additional information that can be added via tags */
    tags?: Flagright.Tag[];
}
