/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Model for User details
 */
export interface UserBase {
    /** Unique user ID */
    userId: string;
    /** Timestamp when userId is created */
    createdTimestamp: number;
}
