/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Flagright from "..";

/**
 * Model for User details
 */
export interface UserOptional {
    userStateDetails?: Flagright.UserStateDetails;
    kycStatusDetails?: Flagright.KycStatusDetails;
    /** User's legal identity documents - See Document Model for details */
    legalDocuments?: Flagright.LegalDocument[];
    contactDetails?: Flagright.ContactDetails;
    transactionLimits?: Flagright.TransactionLimits;
    riskLevel?: Flagright.RiskLevel;
    acquisitionChannel?: Flagright.AcquisitionChannel;
    reasonForAccountOpening?: string[];
    userSegment?: Flagright.UserOptionalUserSegment;
    pepStatus?: Flagright.PepStatus[];
    /** Additional information that can be added via tags */
    tags?: Flagright.Tag[];
}
