/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type UserState = "UNACCEPTABLE" | "TERMINATED" | "ACTIVE" | "DORMANT" | "CREATED" | "SUSPENDED" | "BLOCKED";

export const UserState = {
    Unacceptable: "UNACCEPTABLE",
    Terminated: "TERMINATED",
    Active: "ACTIVE",
    Dormant: "DORMANT",
    Created: "CREATED",
    Suspended: "SUSPENDED",
    Blocked: "BLOCKED",
} as const;
