/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Flagright from "..";

export interface UserRulesResult {
    executedRules?: Flagright.ExecutedRulesResult[];
    hitRules?: Flagright.HitRulesDetails[];
    riskScoreDetails?: Flagright.UserRiskScoreDetails;
}
