/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Flagright from "../index";

export interface UserTagsUpdate {
    userId?: string;
    userType?: Flagright.UserType;
    tags?: Flagright.UserTag[];
}
