/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Flagright } from "@fern-api/flagright";

/**
 * Model for User details
 */
export interface UserBase {
    /** Unique user ID */
    userId: string;
    userDetails?: Flagright.UserDetails;
    /** Timestamp when userId is created */
    createdTimestamp: number;
}
