/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Flagright from "../index";

export interface User {
    /** Unique user ID */
    userId: string;
    /** Timestamp when userId is created */
    createdTimestamp: number;
    /** Timestamp when user was activated */
    activatedTimestamp?: number;
    userDetails?: Flagright.UserDetails;
    userStateDetails?: Flagright.UserStateDetails;
    kycStatusDetails?: Flagright.KycStatusDetails;
    eoddDate?: number;
    employmentStatus?: Flagright.EmploymentStatus;
    occupation?: string;
    /** User's legal identity documents - See Document Model for details */
    legalDocuments?: Flagright.LegalDocument[];
    contactDetails?: Flagright.ContactDetails;
    employmentDetails?: Flagright.EmploymentDetails;
    transactionLimits?: Flagright.TransactionLimits;
    expectedIncome?: Flagright.ExpectedIncome;
    riskLevel?: Flagright.RiskLevel;
    kycRiskLevel?: Flagright.RiskLevel;
    acquisitionChannel?: Flagright.AcquisitionChannel;
    reasonForAccountOpening?: string[];
    sourceOfFunds?: Flagright.SourceOfFunds[];
    userSegment?: Flagright.ConsumerUserSegment;
    pepStatus?: Flagright.PepStatus[];
    sanctionsStatus?: Flagright.SanctionsStatus;
    adverseMediaStatus?: Flagright.AdverseMediaStatus;
    /** Timestamp of the last successful transaction of the user */
    lastTransactionTimestamp?: number;
    linkedEntities?: Flagright.UserEntityLink;
    savedPaymentDetails?: Flagright.UserSavedPaymentDetailsItem[];
    /** Additional information that can be added via tags */
    tags?: Flagright.UserTag[];
    /** Uploaded user's attachment */
    attachments?: Flagright.PersonAttachment[];
    updateCount?: number;
}
