/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type WebhookEventTriggeredBy = "MANUAL" | "SYSTEM";

export const WebhookEventTriggeredBy = {
    Manual: "MANUAL",
    System: "SYSTEM",
} as const;
