/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Flagright from "../index";

export type WebhookEventData =
    | Flagright.UserStateDetails
    | Flagright.CaseClosedDetails
    | Flagright.CaseOpenedDetails
    | Flagright.AlertClosedDetails
    | Flagright.AlertOpenedDetails
    | Flagright.TransactionStatusDetails
    | Flagright.KycStatusDetails
    | Flagright.UserTagsUpdate
    | Flagright.CraRiskLevelUpdatedDetails;
