/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Flagright from "../index";

export interface WebhookKycStatusDetails {
    reason?: string;
    status?: Flagright.KycStatus;
    userId: string;
}
