/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type WebhookEventType =
    | "CASE_CLOSED"
    | "USER_STATE_UPDATED"
    | "ALERT_CLOSED"
    | "TRANSACTION_STATUS_UPDATED"
    | "KYC_STATUS_UPDATED"
    | "CASE_OPENED"
    | "ALERT_OPENED"
    | "PEP_STATUS_UPDATED"
    | "USER_TAGS_UPDATED"
    | "USER_TAGS_DELETED"
    | "CRA_RISK_LEVEL_UPDATED"
    | "LIST_UPDATED"
    | "SANCTIONS_STATUS_UPDATED"
    | "ADVERSE_MEDIA_STATUS_UPDATED"
    | "CASE_ESCALATED"
    | "ALERT_ESCALATED"
    | "BATCH_COMPLETED";
export const WebhookEventType = {
    CaseClosed: "CASE_CLOSED",
    UserStateUpdated: "USER_STATE_UPDATED",
    AlertClosed: "ALERT_CLOSED",
    TransactionStatusUpdated: "TRANSACTION_STATUS_UPDATED",
    KycStatusUpdated: "KYC_STATUS_UPDATED",
    CaseOpened: "CASE_OPENED",
    AlertOpened: "ALERT_OPENED",
    PepStatusUpdated: "PEP_STATUS_UPDATED",
    UserTagsUpdated: "USER_TAGS_UPDATED",
    UserTagsDeleted: "USER_TAGS_DELETED",
    CraRiskLevelUpdated: "CRA_RISK_LEVEL_UPDATED",
    ListUpdated: "LIST_UPDATED",
    SanctionsStatusUpdated: "SANCTIONS_STATUS_UPDATED",
    AdverseMediaStatusUpdated: "ADVERSE_MEDIA_STATUS_UPDATED",
    CaseEscalated: "CASE_ESCALATED",
    AlertEscalated: "ALERT_ESCALATED",
    BatchCompleted: "BATCH_COMPLETED",
} as const;
