/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Flagright from "../../../../api";
import * as core from "../../../../core";

export const TransactionsVerifyResponse: core.serialization.ObjectSchema<
    serializers.TransactionsVerifyResponse.Raw,
    Flagright.TransactionsVerifyResponse
> = core.serialization
    .object({
        message: core.serialization.string().optional(),
    })
    .extend(core.serialization.lazyObject(async () => (await import("../../..")).TransactionMonitoringResult));

export declare namespace TransactionsVerifyResponse {
    interface Raw extends serializers.TransactionMonitoringResult.Raw {
        message?: string | null;
    }
}
