/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Flagright from "../../../..";

/**
 * @example
 *     {
 *         data: [{
 *                 timestamp: 1.1,
 *                 userId: "userId"
 *             }]
 *     }
 */
export interface BusinessUserEventBatchRequest {
    batchId?: string;
    data: Flagright.BusinessUserEvent[];
}
