/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Flagright from "../../../../index";

/**
 * @example
 *     {
 *         lockCraRiskLevel: "true",
 *         lockKycRiskLevel: "true",
 *         data: [{
 *                 timestamp: 1.1,
 *                 userId: "userId"
 *             }]
 *     }
 */
export interface ConsumerUserEventBatchRequest {
    /**
     * Boolean string whether Flagright should lock the CRA risk level for the user.
     */
    lockCraRiskLevel?: Flagright.BooleanString;
    /**
     * Boolean string whether Flagright should lock the KYC risk level for the user.
     */
    lockKycRiskLevel?: Flagright.BooleanString;
    batchId?: string;
    data: Flagright.ConsumerUserEvent[];
}
