/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Flagright from "../../api/index";
import * as core from "../../core";

export const AcquisitionChannel: core.serialization.Schema<
    serializers.AcquisitionChannel.Raw,
    Flagright.AcquisitionChannel
> = core.serialization.enum_(["ORGANIC", "PAID", "REFERRAL", "OFFLINE", "GATHERING", "UNKNOWN"]);

export declare namespace AcquisitionChannel {
    export type Raw = "ORGANIC" | "PAID" | "REFERRAL" | "OFFLINE" | "GATHERING" | "UNKNOWN";
}
