/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Flagright from "../../api/index";
import * as core from "../../core";
import { BusinessOptional } from "./BusinessOptional";
import { ExecutedRulesResult } from "./ExecutedRulesResult";
import { UserRiskScoreDetails } from "./UserRiskScoreDetails";

export const BatchBusinessUserEventWithRulesResult: core.serialization.ObjectSchema<
    serializers.BatchBusinessUserEventWithRulesResult.Raw,
    Flagright.BatchBusinessUserEventWithRulesResult
> = core.serialization.object({
    timestamp: core.serialization.number(),
    userId: core.serialization.string(),
    eventId: core.serialization.string().optional(),
    reason: core.serialization.string().optional(),
    eventDescription: core.serialization.string().optional(),
    updatedBusinessUserAttributes: BusinessOptional.optional(),
    executedRules: core.serialization.list(ExecutedRulesResult).optional(),
    riskScoreDetails: UserRiskScoreDetails.optional(),
});

export declare namespace BatchBusinessUserEventWithRulesResult {
    export interface Raw {
        timestamp: number;
        userId: string;
        eventId?: string | null;
        reason?: string | null;
        eventDescription?: string | null;
        updatedBusinessUserAttributes?: BusinessOptional.Raw | null;
        executedRules?: ExecutedRulesResult.Raw[] | null;
        riskScoreDetails?: UserRiskScoreDetails.Raw | null;
    }
}
