/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Flagright from "../../api/index";
import * as core from "../../core";
import { BatchBusinessUserEventWithRulesResult } from "./BatchBusinessUserEventWithRulesResult";

export const BatchBusinessUserEventsWithRulesResult: core.serialization.ObjectSchema<
    serializers.BatchBusinessUserEventsWithRulesResult.Raw,
    Flagright.BatchBusinessUserEventsWithRulesResult
> = core.serialization.object({
    businessUserEvents: core.serialization.list(BatchBusinessUserEventWithRulesResult),
    totalCount: core.serialization.number(),
});

export declare namespace BatchBusinessUserEventsWithRulesResult {
    export interface Raw {
        businessUserEvents: BatchBusinessUserEventWithRulesResult.Raw[];
        totalCount: number;
    }
}
