/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Flagright from "../../api";
import * as core from "../../core";

export const BatchResponse: core.serialization.ObjectSchema<serializers.BatchResponse.Raw, Flagright.BatchResponse> =
    core.serialization.object({
        message: core.serialization.string().optional(),
        batchId: core.serialization.string().optional(),
        status: core.serialization.string().optional(),
    });

export declare namespace BatchResponse {
    interface Raw {
        message?: string | null;
        batchId?: string | null;
        status?: string | null;
    }
}
