/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Flagright from "../../api/index";
import * as core from "../../core";
import { RuleAction } from "./RuleAction";
import { TransactionRiskScoringResult } from "./TransactionRiskScoringResult";
import { HitRulesDetails } from "./HitRulesDetails";

export const BatchTransactionMonitoringResult: core.serialization.ObjectSchema<
    serializers.BatchTransactionMonitoringResult.Raw,
    Flagright.BatchTransactionMonitoringResult
> = core.serialization.object({
    transactionId: core.serialization.string(),
    status: RuleAction,
    riskScoreDetails: TransactionRiskScoringResult.optional(),
    hitRules: core.serialization.list(HitRulesDetails),
});

export declare namespace BatchTransactionMonitoringResult {
    export interface Raw {
        transactionId: string;
        status: RuleAction.Raw;
        riskScoreDetails?: TransactionRiskScoringResult.Raw | null;
        hitRules: HitRulesDetails.Raw[];
    }
}
