/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Flagright from "../../api/index";
import * as core from "../../core";
import { Person } from "./Person";
import { LegalEntity } from "./LegalEntity";

export const BatchBusinessUserWithRulesResultShareHoldersItem: core.serialization.Schema<
    serializers.BatchBusinessUserWithRulesResultShareHoldersItem.Raw,
    Flagright.BatchBusinessUserWithRulesResultShareHoldersItem
> = core.serialization.undiscriminatedUnion([Person, LegalEntity]);

export declare namespace BatchBusinessUserWithRulesResultShareHoldersItem {
    export type Raw = Person.Raw | LegalEntity.Raw;
}
