/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Flagright from "../../api/index";
import * as core from "../../core";

export const BatchCompletedDetailsType: core.serialization.Schema<
    serializers.BatchCompletedDetailsType.Raw,
    Flagright.BatchCompletedDetailsType
> = core.serialization.enum_(["TRANSACTION_BATCH", "TRANSACTION_EVENT_BATCH", "USER_BATCH", "USER_EVENT_BATCH"]);

export declare namespace BatchCompletedDetailsType {
    export type Raw = "TRANSACTION_BATCH" | "TRANSACTION_EVENT_BATCH" | "USER_BATCH" | "USER_EVENT_BATCH";
}
