/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Flagright from "../../api/index";
import * as core from "../../core";

export const BlockchainRiskSubjectDirection: core.serialization.Schema<
    serializers.BlockchainRiskSubjectDirection.Raw,
    Flagright.BlockchainRiskSubjectDirection
> = core.serialization.enum_(["ORIGIN", "DESTINATION"]);

export declare namespace BlockchainRiskSubjectDirection {
    export type Raw = "ORIGIN" | "DESTINATION";
}
