/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Flagright from "../../api/index";
import * as core from "../../core";
import { Tag } from "./Tag";
import { RiskLevel } from "./RiskLevel";

export const BlockchainRiskCategory: core.serialization.ObjectSchema<
    serializers.BlockchainRiskCategory.Raw,
    Flagright.BlockchainRiskCategory
> = core.serialization.object({
    id: core.serialization.string().optional(),
    name: core.serialization.string().optional(),
    description: core.serialization.string().optional(),
    tags: core.serialization.list(Tag).optional(),
    riskScore: core.serialization.number().optional(),
    riskLevel: RiskLevel.optional(),
});

export declare namespace BlockchainRiskCategory {
    export interface Raw {
        id?: string | null;
        name?: string | null;
        description?: string | null;
        tags?: Tag.Raw[] | null;
        riskScore?: number | null;
        riskLevel?: RiskLevel.Raw | null;
    }
}
