/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Flagright from "../../api/index";
import * as core from "../../core";
import { RiskLevel } from "./RiskLevel";
import { RiskExposureType } from "./RiskExposureType";
import { TransactionAmountDetails } from "./TransactionAmountDetails";

export const BlockchainRiskDetail: core.serialization.ObjectSchema<
    serializers.BlockchainRiskDetail.Raw,
    Flagright.BlockchainRiskDetail
> = core.serialization.object({
    alertId: core.serialization.string().optional(),
    categoryId: core.serialization.string().optional(),
    categoryName: core.serialization.string().optional(),
    categoryRiskLevel: RiskLevel.optional(),
    categoryRiskScore: core.serialization.number().optional(),
    exposureType: RiskExposureType.optional(),
    entity: core.serialization.string().optional(),
    exposureAmount: TransactionAmountDetails.optional(),
});

export declare namespace BlockchainRiskDetail {
    export interface Raw {
        alertId?: string | null;
        categoryId?: string | null;
        categoryName?: string | null;
        categoryRiskLevel?: RiskLevel.Raw | null;
        categoryRiskScore?: number | null;
        exposureType?: RiskExposureType.Raw | null;
        entity?: string | null;
        exposureAmount?: TransactionAmountDetails.Raw | null;
    }
}
