/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Flagright from "../../api";
import * as core from "../../core";

export const Business: core.serialization.ObjectSchema<serializers.Business.Raw, Flagright.Business> =
    core.serialization
        .object({})
        .extend(core.serialization.lazyObject(async () => (await import("..")).BusinessBase))
        .extend(core.serialization.lazyObject(async () => (await import("..")).BusinessOptional));

export declare namespace Business {
    interface Raw extends serializers.BusinessBase.Raw, serializers.BusinessOptional.Raw {}
}
