/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import { Flagright } from "@fern-api/flagright";
import * as core from "../../core";

export const BusinessBase: core.serialization.ObjectSchema<serializers.BusinessBase.Raw, Flagright.BusinessBase> =
    core.serialization.object({
        userId: core.serialization.string(),
        legalEntity: core.serialization.lazyObject(async () => (await import("..")).LegalEntity),
        createdTimestamp: core.serialization.number(),
    });

export declare namespace BusinessBase {
    interface Raw {
        userId: string;
        legalEntity: serializers.LegalEntity.Raw;
        createdTimestamp: number;
    }
}
