/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Flagright from "../../api/index";
import * as core from "../../core";
import { UserStateDetails } from "./UserStateDetails";
import { KycStatusDetails } from "./KycStatusDetails";
import { LegalEntity } from "./LegalEntity";
import { Person } from "./Person";
import { TransactionLimits } from "./TransactionLimits";
import { RiskLevel } from "./RiskLevel";
import { PaymentMethod } from "./PaymentMethod";
import { UserEntityLink } from "./UserEntityLink";
import { AcquisitionChannel } from "./AcquisitionChannel";
import { BusinessOptionalSavedPaymentDetailsItem } from "./BusinessOptionalSavedPaymentDetailsItem";
import { MccDetails } from "./MccDetails";
import { UserTag } from "./UserTag";
import { PersonAttachment } from "./PersonAttachment";

export const BusinessOptional: core.serialization.ObjectSchema<
    serializers.BusinessOptional.Raw,
    Flagright.BusinessOptional
> = core.serialization.object({
    activatedTimestamp: core.serialization.number().optional(),
    userStateDetails: UserStateDetails.optional(),
    kycStatusDetails: KycStatusDetails.optional(),
    legalEntity: LegalEntity.optional(),
    shareHolders: core.serialization.list(Person).optional(),
    directors: core.serialization.list(Person).optional(),
    transactionLimits: TransactionLimits.optional(),
    riskLevel: RiskLevel.optional(),
    kycRiskLevel: RiskLevel.optional(),
    allowedPaymentMethods: core.serialization.list(PaymentMethod).optional(),
    lastTransactionTimestamp: core.serialization.number().optional(),
    linkedEntities: UserEntityLink.optional(),
    acquisitionChannel: AcquisitionChannel.optional(),
    savedPaymentDetails: core.serialization.list(BusinessOptionalSavedPaymentDetailsItem).optional(),
    mccDetails: MccDetails.optional(),
    tags: core.serialization.list(UserTag).optional(),
    attachments: core.serialization.list(PersonAttachment).optional(),
});

export declare namespace BusinessOptional {
    export interface Raw {
        activatedTimestamp?: number | null;
        userStateDetails?: UserStateDetails.Raw | null;
        kycStatusDetails?: KycStatusDetails.Raw | null;
        legalEntity?: LegalEntity.Raw | null;
        shareHolders?: Person.Raw[] | null;
        directors?: Person.Raw[] | null;
        transactionLimits?: TransactionLimits.Raw | null;
        riskLevel?: RiskLevel.Raw | null;
        kycRiskLevel?: RiskLevel.Raw | null;
        allowedPaymentMethods?: PaymentMethod.Raw[] | null;
        lastTransactionTimestamp?: number | null;
        linkedEntities?: UserEntityLink.Raw | null;
        acquisitionChannel?: AcquisitionChannel.Raw | null;
        savedPaymentDetails?: BusinessOptionalSavedPaymentDetailsItem.Raw[] | null;
        mccDetails?: MccDetails.Raw | null;
        tags?: UserTag.Raw[] | null;
        attachments?: PersonAttachment.Raw[] | null;
    }
}
