/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import { Flagright } from "@fern-api/flagright";
import * as core from "../../core";

export const BusinessUsersResponse: core.serialization.ObjectSchema<
    serializers.BusinessUsersResponse.Raw,
    Flagright.BusinessUsersResponse
> = core.serialization.object({
    userId: core.serialization.string(),
    userRiskScoreDetails: core.serialization.lazyObject(async () => (await import("..")).RiskScoringResult).optional(),
});

export declare namespace BusinessUsersResponse {
    interface Raw {
        userId: string;
        userRiskScoreDetails?: serializers.RiskScoringResult.Raw | null;
    }
}
