/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Flagright from "../../api/index";
import * as core from "../../core";
import { PersonWithRole } from "./PersonWithRole";
import { LegalEntityWithRole } from "./LegalEntityWithRole";

export const BusinessOptionalAssociatedPartiesItem: core.serialization.Schema<
    serializers.BusinessOptionalAssociatedPartiesItem.Raw,
    Flagright.BusinessOptionalAssociatedPartiesItem
> = core.serialization.undiscriminatedUnion([PersonWithRole, LegalEntityWithRole]);

export declare namespace BusinessOptionalAssociatedPartiesItem {
    export type Raw = PersonWithRole.Raw | LegalEntityWithRole.Raw;
}
