/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Flagright from "../../api/index";
import * as core from "../../core";
import { PersonWithRole } from "./PersonWithRole";
import { LegalEntityWithRole } from "./LegalEntityWithRole";

export const BusinessAssociatedPartiesItem: core.serialization.Schema<
    serializers.BusinessAssociatedPartiesItem.Raw,
    Flagright.BusinessAssociatedPartiesItem
> = core.serialization.undiscriminatedUnion([PersonWithRole, LegalEntityWithRole]);

export declare namespace BusinessAssociatedPartiesItem {
    export type Raw = PersonWithRole.Raw | LegalEntityWithRole.Raw;
}
