/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Flagright from "../../api";
import * as core from "../../core";

export const BusinessResponse: core.serialization.ObjectSchema<
    serializers.BusinessResponse.Raw,
    Flagright.BusinessResponse
> = core.serialization
    .object({
        riskScoreDetails: core.serialization.lazyObject(async () => (await import("..")).RiskScoreDetails).optional(),
    })
    .extend(core.serialization.lazyObject(async () => (await import("..")).BusinessWithRulesResult));

export declare namespace BusinessResponse {
    interface Raw extends serializers.BusinessWithRulesResult.Raw {
        riskScoreDetails?: serializers.RiskScoreDetails.Raw | null;
    }
}
