/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Flagright from "../../api/index";
import * as core from "../../core";
import { EmailId } from "./EmailId";
import { CardStatus } from "./CardStatus";
import { CountryCode } from "./CountryCode";
import { ConsumerName } from "./ConsumerName";
import { CardExpiry } from "./CardExpiry";
import { PosDetails } from "./PosDetails";
import { CardBrand } from "./CardBrand";
import { CardFunding } from "./CardFunding";
import { CardType } from "./CardType";
import { Amount } from "./Amount";
import { CardMerchantDetails } from "./CardMerchantDetails";
import { Address } from "./Address";
import { Tag } from "./Tag";

export const CardDetails: core.serialization.ObjectSchema<serializers.CardDetails.Raw, Flagright.CardDetails> =
    core.serialization.object({
        cardFingerprint: core.serialization.string().optional(),
        emailId: EmailId.optional(),
        cardStatus: CardStatus.optional(),
        cardIssuedCountry: CountryCode.optional(),
        transactionReferenceField: core.serialization.string().optional(),
        "3DsDone": core.serialization.property("3dsDone", core.serialization.boolean().optional()),
        nameOnCard: ConsumerName.optional(),
        cardExpiry: CardExpiry.optional(),
        posDetails: PosDetails.optional(),
        cardLast4Digits: core.serialization.string().optional(),
        cardBrand: CardBrand.optional(),
        cardFunding: CardFunding.optional(),
        cardAuthenticated: core.serialization.boolean().optional(),
        cardTokenized: core.serialization.boolean().optional(),
        cardPresent: core.serialization.boolean().optional(),
        paymentChannel: core.serialization.string().optional(),
        cardType: CardType.optional(),
        cardBalance: Amount.optional(),
        merchantDetails: CardMerchantDetails.optional(),
        networkProviderRiskScore: core.serialization.number().optional(),
        address: Address.optional(),
        tags: core.serialization.list(Tag).optional(),
    });

export declare namespace CardDetails {
    export interface Raw {
        cardFingerprint?: string | null;
        emailId?: EmailId.Raw | null;
        cardStatus?: CardStatus.Raw | null;
        cardIssuedCountry?: CountryCode.Raw | null;
        transactionReferenceField?: string | null;
        "3dsDone"?: boolean | null;
        nameOnCard?: ConsumerName.Raw | null;
        cardExpiry?: CardExpiry.Raw | null;
        posDetails?: PosDetails.Raw | null;
        cardLast4Digits?: string | null;
        cardBrand?: CardBrand.Raw | null;
        cardFunding?: CardFunding.Raw | null;
        cardAuthenticated?: boolean | null;
        cardTokenized?: boolean | null;
        cardPresent?: boolean | null;
        paymentChannel?: string | null;
        cardType?: CardType.Raw | null;
        cardBalance?: Amount.Raw | null;
        merchantDetails?: CardMerchantDetails.Raw | null;
        networkProviderRiskScore?: number | null;
        address?: Address.Raw | null;
        tags?: Tag.Raw[] | null;
    }
}
