/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Flagright from "../../api";
import * as core from "../../core";

export const CardDetailsCardBrand: core.serialization.Schema<
    serializers.CardDetailsCardBrand.Raw,
    Flagright.CardDetailsCardBrand
> = core.serialization.enum_(["VISA", "MASTERCARD", "AMERICAN_EXPRESS", "DISCOVER", "UNIONPAY", "RUPAY", "JCB"]);

export declare namespace CardDetailsCardBrand {
    type Raw = "VISA" | "MASTERCARD" | "AMERICAN_EXPRESS" | "DISCOVER" | "UNIONPAY" | "RUPAY" | "JCB";
}
