/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Flagright from "../../api/index";
import * as core from "../../core";

export const CardType: core.serialization.Schema<serializers.CardType.Raw, Flagright.CardType> =
    core.serialization.enum_(["VIRTUAL", "PHYSICAL"]);

export declare namespace CardType {
    export type Raw = "VIRTUAL" | "PHYSICAL";
}
