/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Flagright from "../../api/index";
import * as core from "../../core";

export const CardPaymentMethod: core.serialization.Schema<
    serializers.CardPaymentMethod.Raw,
    Flagright.CardPaymentMethod
> = core.serialization.stringLiteral("CARD");

export declare namespace CardPaymentMethod {
    export type Raw = "CARD";
}
