/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Flagright from "../../api/index";
import * as core from "../../core";
import { CaseManagementEventCaseStatus } from "./CaseManagementEventCaseStatus";
import { CaseManagementEventCaseStatusReason } from "./CaseManagementEventCaseStatusReason";

export const CaseManagementEvent: core.serialization.ObjectSchema<
    serializers.CaseManagementEvent.Raw,
    Flagright.CaseManagementEvent
> = core.serialization.object({
    caseStatus: CaseManagementEventCaseStatus,
    timestamp: core.serialization.number(),
    caseStatusReason: CaseManagementEventCaseStatusReason,
    transactionId: core.serialization.string().optional(),
    userId: core.serialization.string().optional(),
    eventId: core.serialization.string().optional(),
    caseStatusReasonDescription: core.serialization.string().optional(),
});

export declare namespace CaseManagementEvent {
    export interface Raw {
        caseStatus: CaseManagementEventCaseStatus.Raw;
        timestamp: number;
        caseStatusReason: CaseManagementEventCaseStatusReason.Raw;
        transactionId?: string | null;
        userId?: string | null;
        eventId?: string | null;
        caseStatusReasonDescription?: string | null;
    }
}
