/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Flagright from "../../api/index";
import * as core from "../../core";

export const CaseManagementEventCaseStatus: core.serialization.Schema<
    serializers.CaseManagementEventCaseStatus.Raw,
    Flagright.CaseManagementEventCaseStatus
> = core.serialization.enum_(["CLOSED", "HIT"]);

export declare namespace CaseManagementEventCaseStatus {
    export type Raw = "CLOSED" | "HIT";
}
