/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Flagright from "../../api/index";
import * as core from "../../core";
import { Tag } from "./Tag";

export const CaseTagsUpdate: core.serialization.ObjectSchema<serializers.CaseTagsUpdate.Raw, Flagright.CaseTagsUpdate> =
    core.serialization.object({
        caseId: core.serialization.string().optional(),
        tags: core.serialization.list(Tag).optional(),
    });

export declare namespace CaseTagsUpdate {
    export interface Raw {
        caseId?: string | null;
        tags?: Tag.Raw[] | null;
    }
}
