/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Flagright from "../../api/index";
import * as core from "../../core";

export const CashPaymentMethod: core.serialization.Schema<
    serializers.CashPaymentMethod.Raw,
    Flagright.CashPaymentMethod
> = core.serialization.stringLiteral("CASH");

export declare namespace CashPaymentMethod {
    export type Raw = "CASH";
}
