/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Flagright from "../../api";
import * as core from "../../core";

export const CashDetails: core.serialization.ObjectSchema<serializers.CashDetails.Raw, Flagright.CashDetails> =
    core.serialization.object({
        identifier: core.serialization.string().optional(),
    });

export declare namespace CashDetails {
    interface Raw {
        identifier?: string | null;
    }
}
