/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Flagright from "../../api/index";
import * as core from "../../core";

export const ColumnType: core.serialization.Schema<serializers.ColumnType.Raw, Flagright.ColumnType> =
    core.serialization.enum_(["STRING", "NUMBER", "DATE"]);

export declare namespace ColumnType {
    export type Raw = "STRING" | "NUMBER" | "DATE";
}
