/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Flagright from "../../api/index";
import * as core from "../../core";
import { CountryCode } from "./CountryCode";
import { Tag } from "./Tag";

export const CompanyRegistrationDetails: core.serialization.ObjectSchema<
    serializers.CompanyRegistrationDetails.Raw,
    Flagright.CompanyRegistrationDetails
> = core.serialization.object({
    registrationIdentifier: core.serialization.string().optional(),
    registrationCountry: CountryCode.optional(),
    taxResidenceCountry: CountryCode.optional(),
    taxIdentifier: core.serialization.string().optional(),
    legalEntityType: core.serialization.string().optional(),
    dateOfRegistration: core.serialization.string().optional(),
    tags: core.serialization.list(Tag).optional(),
});

export declare namespace CompanyRegistrationDetails {
    export interface Raw {
        registrationIdentifier?: string | null;
        registrationCountry?: CountryCode.Raw | null;
        taxResidenceCountry?: CountryCode.Raw | null;
        taxIdentifier?: string | null;
        legalEntityType?: string | null;
        dateOfRegistration?: string | null;
        tags?: Tag.Raw[] | null;
    }
}
