/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Flagright from "../../api";
import * as core from "../../core";

export const CompanyGeneralDetailsUserSegment: core.serialization.Schema<
    serializers.CompanyGeneralDetailsUserSegment.Raw,
    Flagright.CompanyGeneralDetailsUserSegment
> = core.serialization.enum_(["SOLE_PROPRIETORSHIP", "SMB", "SMALL", "MEDIUM", "LARGE", "UNKNOWN"]);

export declare namespace CompanyGeneralDetailsUserSegment {
    type Raw = "SOLE_PROPRIETORSHIP" | "SMB" | "SMALL" | "MEDIUM" | "LARGE" | "UNKNOWN";
}
