/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Flagright from "../../api";
import * as core from "../../core";

export const ConsumerUserMonitoringResult: core.serialization.ObjectSchema<
    serializers.ConsumerUserMonitoringResult.Raw,
    Flagright.ConsumerUserMonitoringResult
> = core.serialization.object({
    userId: core.serialization.string(),
    riskScoreDetails: core.serialization.lazyObject(async () => (await import("..")).UserRiskScoreDetails).optional(),
    hitRules: core.serialization
        .list(core.serialization.lazyObject(async () => (await import("..")).HitRulesDetails))
        .optional(),
    executedRules: core.serialization
        .list(core.serialization.lazyObject(async () => (await import("..")).ExecutedRulesResult))
        .optional(),
});

export declare namespace ConsumerUserMonitoringResult {
    interface Raw {
        userId: string;
        riskScoreDetails?: serializers.UserRiskScoreDetails.Raw | null;
        hitRules?: serializers.HitRulesDetails.Raw[] | null;
        executedRules?: serializers.ExecutedRulesResult.Raw[] | null;
    }
}
