/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Flagright from "../../api/index";
import * as core from "../../core";
import { UserRiskScoreDetails } from "./UserRiskScoreDetails";
import { HitRulesDetails } from "./HitRulesDetails";
import { ExecutedRulesResult } from "./ExecutedRulesResult";

export const ConsumerUserMonitoringResult: core.serialization.ObjectSchema<
    serializers.ConsumerUserMonitoringResult.Raw,
    Flagright.ConsumerUserMonitoringResult
> = core.serialization.object({
    userId: core.serialization.string(),
    riskScoreDetails: UserRiskScoreDetails.optional(),
    hitRules: core.serialization.list(HitRulesDetails).optional(),
    executedRules: core.serialization.list(ExecutedRulesResult).optional(),
});

export declare namespace ConsumerUserMonitoringResult {
    export interface Raw {
        userId: string;
        riskScoreDetails?: UserRiskScoreDetails.Raw | null;
        hitRules?: HitRulesDetails.Raw[] | null;
        executedRules?: ExecutedRulesResult.Raw[] | null;
    }
}
