/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Flagright from "../../api/index";
import * as core from "../../core";
import { Address } from "./Address";
import { Tag } from "./Tag";

export const CorrespondentBankDetails: core.serialization.ObjectSchema<
    serializers.CorrespondentBankDetails.Raw,
    Flagright.CorrespondentBankDetails
> = core.serialization.object({
    bankName: core.serialization.string().optional(),
    bankAddress: Address.optional(),
    swiftCode: core.serialization.string().optional(),
    tags: core.serialization.list(Tag).optional(),
});

export declare namespace CorrespondentBankDetails {
    export interface Raw {
        bankName?: string | null;
        bankAddress?: Address.Raw | null;
        swiftCode?: string | null;
        tags?: Tag.Raw[] | null;
    }
}
