/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Flagright from "../../api/index";
import * as core from "../../core";

export const CraRiskLevelUpdatedRiskFactor: core.serialization.ObjectSchema<
    serializers.CraRiskLevelUpdatedRiskFactor.Raw,
    Flagright.CraRiskLevelUpdatedRiskFactor
> = core.serialization.object({
    riskFactorId: core.serialization.string().optional(),
    riskFactorVersionId: core.serialization.string().optional(),
    value: core.serialization.string().optional(),
    riskScore: core.serialization.number().optional(),
    riskLevel: core.serialization.string().optional(),
    weight: core.serialization.number().optional(),
});

export declare namespace CraRiskLevelUpdatedRiskFactor {
    export interface Raw {
        riskFactorId?: string | null;
        riskFactorVersionId?: string | null;
        value?: string | null;
        riskScore?: number | null;
        riskLevel?: string | null;
        weight?: number | null;
    }
}
