/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Flagright from "../../api/index";
import * as core from "../../core";
import { ColumnType } from "./ColumnType";

export const CustomColumn: core.serialization.ObjectSchema<serializers.CustomColumn.Raw, Flagright.CustomColumn> =
    core.serialization.object({
        key: core.serialization.string(),
        type: ColumnType,
    });

export declare namespace CustomColumn {
    export interface Raw {
        key: string;
        type: ColumnType.Raw;
    }
}
