/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Flagright from "../../api/index";
import * as core from "../../core";
import { RuleHitDirection } from "./RuleHitDirection";

export const ExecutedLogicVars: core.serialization.ObjectSchema<
    serializers.ExecutedLogicVars.Raw,
    Flagright.ExecutedLogicVars
> = core.serialization.object({
    direction: RuleHitDirection.optional(),
    value: core.serialization.record(core.serialization.string(), core.serialization.unknown()),
});

export declare namespace ExecutedLogicVars {
    export interface Raw {
        direction?: RuleHitDirection.Raw | null;
        value: Record<string, unknown>;
    }
}
