/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Flagright from "../../api/index";
import * as core from "../../core";
import { ExpectedTransactionCurrency } from "./ExpectedTransactionCurrency";

export const ExpectedTransactionCurrencies: core.serialization.ObjectSchema<
    serializers.ExpectedTransactionCurrencies.Raw,
    Flagright.ExpectedTransactionCurrencies
> = core.serialization.object({
    incoming: core.serialization.list(ExpectedTransactionCurrency).optional(),
    outgoing: core.serialization.list(ExpectedTransactionCurrency).optional(),
});

export declare namespace ExpectedTransactionCurrencies {
    export interface Raw {
        incoming?: ExpectedTransactionCurrency.Raw[] | null;
        outgoing?: ExpectedTransactionCurrency.Raw[] | null;
    }
}
