/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Flagright from "../../api/index";
import * as core from "../../core";
import { RuleFailureException } from "./RuleFailureException";

export const FailedRulesResult: core.serialization.ObjectSchema<
    serializers.FailedRulesResult.Raw,
    Flagright.FailedRulesResult
> = core.serialization.object({
    ruleId: core.serialization.string(),
    ruleName: core.serialization.string(),
    ruleDescription: core.serialization.string(),
    failureException: RuleFailureException,
});

export declare namespace FailedRulesResult {
    export interface Raw {
        ruleId: string;
        ruleName: string;
        ruleDescription: string;
        failureException: RuleFailureException.Raw;
    }
}
