/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Flagright from "../../api/index";
import * as core from "../../core";
import { CompanyGeneralDetails } from "./CompanyGeneralDetails";
import { CompanyFinancialDetails } from "./CompanyFinancialDetails";
import { CompanyRegistrationDetails } from "./CompanyRegistrationDetails";
import { SourceOfFunds } from "./SourceOfFunds";
import { ContactDetails } from "./ContactDetails";
import { Tag } from "./Tag";
import { PepStatus } from "./PepStatus";

export const LegalEntity: core.serialization.ObjectSchema<serializers.LegalEntity.Raw, Flagright.LegalEntity> =
    core.serialization.object({
        companyGeneralDetails: CompanyGeneralDetails,
        companyFinancialDetails: CompanyFinancialDetails.optional(),
        companyRegistrationDetails: CompanyRegistrationDetails.optional(),
        reasonForAccountOpening: core.serialization.list(core.serialization.string()).optional(),
        sourceOfFunds: core.serialization.list(SourceOfFunds).optional(),
        contactDetails: ContactDetails.optional(),
        tags: core.serialization.list(Tag).optional(),
        pepStatus: core.serialization.list(PepStatus).optional(),
    });

export declare namespace LegalEntity {
    export interface Raw {
        companyGeneralDetails: CompanyGeneralDetails.Raw;
        companyFinancialDetails?: CompanyFinancialDetails.Raw | null;
        companyRegistrationDetails?: CompanyRegistrationDetails.Raw | null;
        reasonForAccountOpening?: string[] | null;
        sourceOfFunds?: SourceOfFunds.Raw[] | null;
        contactDetails?: ContactDetails.Raw | null;
        tags?: Tag.Raw[] | null;
        pepStatus?: PepStatus.Raw[] | null;
    }
}
