/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Flagright from "../../api/index";
import * as core from "../../core";
import { RuleHitDirection } from "./RuleHitDirection";
import { ListMatchedEntity } from "./ListMatchedEntity";

export const ListContext: core.serialization.ObjectSchema<serializers.ListContext.Raw, Flagright.ListContext> =
    core.serialization.object({
        direction: RuleHitDirection,
        matchedEntities: core.serialization.list(ListMatchedEntity),
    });

export declare namespace ListContext {
    export interface Raw {
        direction: RuleHitDirection.Raw;
        matchedEntities: ListMatchedEntity.Raw[];
    }
}
