/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Flagright from "../../api";
import * as core from "../../core";

export const ListExisted: core.serialization.ObjectSchema<serializers.ListExisted.Raw, Flagright.ListExisted> =
    core.serialization.object({
        listId: core.serialization.string(),
        header: core.serialization.lazyObject(async () => (await import("..")).ListHeader),
        items: core.serialization.list(core.serialization.lazyObject(async () => (await import("..")).ListItem)),
    });

export declare namespace ListExisted {
    interface Raw {
        listId: string;
        header: serializers.ListHeader.Raw;
        items: serializers.ListItem.Raw[];
    }
}
