/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Flagright from "../../api/index";
import * as core from "../../core";
import { ListMetadataTtlUnit } from "./ListMetadataTtlUnit";

export const ListMetadataTtl: core.serialization.ObjectSchema<
    serializers.ListMetadataTtl.Raw,
    Flagright.ListMetadataTtl
> = core.serialization.object({
    unit: ListMetadataTtlUnit,
    value: core.serialization.number(),
});

export declare namespace ListMetadataTtl {
    export interface Raw {
        unit: ListMetadataTtlUnit.Raw;
        value: number;
    }
}
