/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Flagright from "../../api";
import * as core from "../../core";

export const ListSubtype: core.serialization.Schema<serializers.ListSubtype.Raw, Flagright.ListSubtype> =
    core.serialization.enum_([
        "USER_ID",
        "CARD_FINGERPRINT_NUMBER",
        "IBAN_NUMBER",
        "BANK_ACCOUNT_NUMBER",
        "ACH_ACCOUNT_NUMBER",
        "SWIFT_ACCOUNT_NUMBER",
        "BIC",
        "BANK_SWIFT_CODE",
        "UPI_IDENTIFYING_NUMBER",
        "IP_ADDRESS",
        "STRING",
    ]);

export declare namespace ListSubtype {
    type Raw =
        | "USER_ID"
        | "CARD_FINGERPRINT_NUMBER"
        | "IBAN_NUMBER"
        | "BANK_ACCOUNT_NUMBER"
        | "ACH_ACCOUNT_NUMBER"
        | "SWIFT_ACCOUNT_NUMBER"
        | "BIC"
        | "BANK_SWIFT_CODE"
        | "UPI_IDENTIFYING_NUMBER"
        | "IP_ADDRESS"
        | "STRING";
}
