/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Flagright from "../../api";
import * as core from "../../core";

export const MccDetails: core.serialization.ObjectSchema<serializers.MccDetails.Raw, Flagright.MccDetails> =
    core.serialization.object({
        code: core.serialization.number(),
        description: core.serialization.string().optional(),
    });

export declare namespace MccDetails {
    interface Raw {
        code: number;
        description?: string | null;
    }
}
