/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Flagright from "../../api/index";
import * as core from "../../core";

export const MpesaTransactionType: core.serialization.Schema<
    serializers.MpesaTransactionType.Raw,
    Flagright.MpesaTransactionType
> = core.serialization.enum_([
    "CustomerPayBillOnline",
    "CustomerBuyGoodsOnline",
    "SalaryPayment",
    "BusinessPayment",
    "PromotionPayment",
]);

export declare namespace MpesaTransactionType {
    export type Raw =
        | "CustomerPayBillOnline"
        | "CustomerBuyGoodsOnline"
        | "SalaryPayment"
        | "BusinessPayment"
        | "PromotionPayment";
}
