/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Flagright from "../../api/index";
import * as core from "../../core";

export const PepRank: core.serialization.Schema<serializers.PepRank.Raw, Flagright.PepRank> = core.serialization.enum_([
    "LEVEL_1",
    "LEVEL_2",
    "LEVEL_3",
]);

export declare namespace PepRank {
    export type Raw = "LEVEL_1" | "LEVEL_2" | "LEVEL_3";
}
