/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import { Flagright } from "flagright";
import * as core from "../../core";

export const PepStatus: core.serialization.Schema<serializers.PepStatus.Raw, Flagright.PepStatus> =
    core.serialization.enum_(["SUCCESSFUL", "FAILED", "NOT_STARTED", "IN_PROGRESS", "MANUAL_REVIEW"]);

export declare namespace PepStatus {
    type Raw = "SUCCESSFUL" | "FAILED" | "NOT_STARTED" | "IN_PROGRESS" | "MANUAL_REVIEW";
}
