/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Flagright from "../../api/index";
import * as core from "../../core";
import { CountryCode } from "./CountryCode";
import { PepRank } from "./PepRank";

export const PepStatus: core.serialization.ObjectSchema<serializers.PepStatus.Raw, Flagright.PepStatus> =
    core.serialization.object({
        isPepHit: core.serialization.boolean(),
        pepCountry: CountryCode.optional(),
        pepRank: PepRank.optional(),
    });

export declare namespace PepStatus {
    export interface Raw {
        isPepHit: boolean;
        pepCountry?: CountryCode.Raw | null;
        pepRank?: PepRank.Raw | null;
    }
}
