/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Flagright from "../../api";
import * as core from "../../core";

export const PlaceOfBirth: core.serialization.ObjectSchema<serializers.PlaceOfBirth.Raw, Flagright.PlaceOfBirth> =
    core.serialization.object({
        city: core.serialization.string().optional(),
        state: core.serialization.string().optional(),
        country: core.serialization.lazy(async () => (await import("..")).CountryCode),
    });

export declare namespace PlaceOfBirth {
    interface Raw {
        city?: string | null;
        state?: string | null;
        country: serializers.CountryCode.Raw;
    }
}
