/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Flagright from "../../api";
import * as core from "../../core";

export const PostBusinessUserResponse: core.serialization.ObjectSchema<
    serializers.PostBusinessUserResponse.Raw,
    Flagright.PostBusinessUserResponse
> = core.serialization
    .object({
        message: core.serialization.string().optional(),
        userId: core.serialization.string(),
    })
    .extend(core.serialization.lazyObject(async () => (await import("..")).RulesResults));

export declare namespace PostBusinessUserResponse {
    interface Raw extends serializers.RulesResults.Raw {
        message?: string | null;
        userId: string;
    }
}
