/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Flagright from "../../api";
import * as core from "../../core";

export const RuleFailureException: core.serialization.ObjectSchema<
    serializers.RuleFailureException.Raw,
    Flagright.RuleFailureException
> = core.serialization.object({
    exceptionName: core.serialization.string(),
    exceptionDescription: core.serialization.string(),
});

export declare namespace RuleFailureException {
    interface Raw {
        exceptionName: string;
        exceptionDescription: string;
    }
}
