/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Flagright from "../../api/index";
import * as core from "../../core";
import { ExecutedRulesResult } from "./ExecutedRulesResult";
import { HitRulesDetails } from "./HitRulesDetails";

export const RulesResults: core.serialization.ObjectSchema<serializers.RulesResults.Raw, Flagright.RulesResults> =
    core.serialization.object({
        executedRules: core.serialization.list(ExecutedRulesResult),
        hitRules: core.serialization.list(HitRulesDetails),
    });

export declare namespace RulesResults {
    export interface Raw {
        executedRules: ExecutedRulesResult.Raw[];
        hitRules: HitRulesDetails.Raw[];
    }
}
