/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Flagright from "../../api";
import * as core from "../../core";

export const SanctionsDetails: core.serialization.ObjectSchema<
    serializers.SanctionsDetails.Raw,
    Flagright.SanctionsDetails
> = core.serialization.object({
    name: core.serialization.string(),
    searchId: core.serialization.string(),
    entityType: core.serialization.lazy(async () => (await import("..")).SanctionsDetailsEntityType).optional(),
});

export declare namespace SanctionsDetails {
    interface Raw {
        name: string;
        searchId: string;
        entityType?: serializers.SanctionsDetailsEntityType.Raw | null;
    }
}
