/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Flagright from "../../api";
import * as core from "../../core";

export const SanctionsDetailsEntityType: core.serialization.Schema<
    serializers.SanctionsDetailsEntityType.Raw,
    Flagright.SanctionsDetailsEntityType
> = core.serialization.enum_([
    "CONSUMER_NAME",
    "LEGAL_NAME",
    "SHAREHOLDER",
    "DIRECTOR",
    "NAME_ON_CARD",
    "PAYMENT_NAME",
    "PAYMENT_BENEFICIARY_NAME",
    "BANK_NAME",
    "BANK_ACCOUNT_HOLDER_NAME",
]);

export declare namespace SanctionsDetailsEntityType {
    type Raw =
        | "CONSUMER_NAME"
        | "LEGAL_NAME"
        | "SHAREHOLDER"
        | "DIRECTOR"
        | "NAME_ON_CARD"
        | "PAYMENT_NAME"
        | "PAYMENT_BENEFICIARY_NAME"
        | "BANK_NAME"
        | "BANK_ACCOUNT_HOLDER_NAME";
}
