/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Flagright from "../../api";
import * as core from "../../core";

export const SanctionsDetails: core.serialization.ObjectSchema<
    serializers.SanctionsDetails.Raw,
    Flagright.SanctionsDetails
> = core.serialization.object({
    name: core.serialization.string(),
    searchId: core.serialization.string(),
    iban: core.serialization.string().optional(),
    entityType: core.serialization.lazy(async () => (await import("..")).SanctionsDetailsEntityType).optional(),
    sanctionHitIds: core.serialization.list(core.serialization.string()).optional(),
    hitContext: core.serialization.lazyObject(async () => (await import("..")).SanctionsHitContext).optional(),
});

export declare namespace SanctionsDetails {
    interface Raw {
        name: string;
        searchId: string;
        iban?: string | null;
        entityType?: serializers.SanctionsDetailsEntityType.Raw | null;
        sanctionHitIds?: string[] | null;
        hitContext?: serializers.SanctionsHitContext.Raw | null;
    }
}
