/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Flagright from "../../api/index";
import * as core from "../../core";

export const SarReportStatus: core.serialization.Schema<serializers.SarReportStatus.Raw, Flagright.SarReportStatus> =
    core.serialization.enum_([
        "DRAFT",
        "SUBMITTING",
        "SUBMISSION_ACCEPTED",
        "SUBMISSION_REJECTED",
        "SUBMISSION_SUCCESSFUL",
        "COMPLETE",
    ]);

export declare namespace SarReportStatus {
    export type Raw =
        | "DRAFT"
        | "SUBMITTING"
        | "SUBMISSION_ACCEPTED"
        | "SUBMISSION_REJECTED"
        | "SUBMISSION_SUCCESSFUL"
        | "COMPLETE";
}
