/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Flagright from "../../api/index";
import * as core from "../../core";
import { CounterpartyType } from "./CounterpartyType";
import { Amount } from "./Amount";
import { Address } from "./Address";
import { CountryCode } from "./CountryCode";
import { EmailId } from "./EmailId";
import { CorrespondentBankDetails } from "./CorrespondentBankDetails";
import { Tag } from "./Tag";

export const SwiftDetails: core.serialization.ObjectSchema<serializers.SwiftDetails.Raw, Flagright.SwiftDetails> =
    core.serialization.object({
        counterpartyType: CounterpartyType.optional(),
        swiftCode: core.serialization.string().optional(),
        accountNumber: core.serialization.string().optional(),
        routingNumber: core.serialization.string().optional(),
        accountBalance: Amount.optional(),
        accountType: core.serialization.string().optional(),
        bankName: core.serialization.string().optional(),
        name: core.serialization.string().optional(),
        bankAddress: Address.optional(),
        countryOfNationality: CountryCode.optional(),
        countryOfResidence: CountryCode.optional(),
        emailId: EmailId.optional(),
        specialInstructions: core.serialization.string().optional(),
        address: Address.optional(),
        correspondentBankDetails: core.serialization.list(CorrespondentBankDetails).optional(),
        tags: core.serialization.list(Tag).optional(),
    });

export declare namespace SwiftDetails {
    export interface Raw {
        counterpartyType?: CounterpartyType.Raw | null;
        swiftCode?: string | null;
        accountNumber?: string | null;
        routingNumber?: string | null;
        accountBalance?: Amount.Raw | null;
        accountType?: string | null;
        bankName?: string | null;
        name?: string | null;
        bankAddress?: Address.Raw | null;
        countryOfNationality?: CountryCode.Raw | null;
        countryOfResidence?: CountryCode.Raw | null;
        emailId?: EmailId.Raw | null;
        specialInstructions?: string | null;
        address?: Address.Raw | null;
        correspondentBankDetails?: CorrespondentBankDetails.Raw[] | null;
        tags?: Tag.Raw[] | null;
    }
}
