/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Flagright from "../../api";
import * as core from "../../core";

export const TransactionRiskScoringResult: core.serialization.ObjectSchema<
    serializers.TransactionRiskScoringResult.Raw,
    Flagright.TransactionRiskScoringResult
> = core.serialization.object({
    trsScore: core.serialization.number(),
    trsRiskLevel: core.serialization.lazy(async () => (await import("..")).RiskLevel),
});

export declare namespace TransactionRiskScoringResult {
    interface Raw {
        trsScore: number;
        trsRiskLevel: serializers.RiskLevel.Raw;
    }
}
