/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Flagright from "../../api/index";
import * as core from "../../core";
import { RiskLevel } from "./RiskLevel";

export const TransactionRiskScoringResult: core.serialization.ObjectSchema<
    serializers.TransactionRiskScoringResult.Raw,
    Flagright.TransactionRiskScoringResult
> = core.serialization.object({
    trsScore: core.serialization.number(),
    trsRiskLevel: RiskLevel,
    originUserCraRiskScore: core.serialization.number().optional(),
    destinationUserCraRiskScore: core.serialization.number().optional(),
    originUserCraRiskLevel: RiskLevel.optional(),
    destinationUserCraRiskLevel: RiskLevel.optional(),
});

export declare namespace TransactionRiskScoringResult {
    export interface Raw {
        trsScore: number;
        trsRiskLevel: RiskLevel.Raw;
        originUserCraRiskScore?: number | null;
        destinationUserCraRiskScore?: number | null;
        originUserCraRiskLevel?: RiskLevel.Raw | null;
        destinationUserCraRiskLevel?: RiskLevel.Raw | null;
    }
}
