/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Flagright from "../../api/index";
import * as core from "../../core";

export const TransactionType: core.serialization.Schema<serializers.TransactionType.Raw, Flagright.TransactionType> =
    core.serialization.enum_(["DEPOSIT", "TRANSFER", "EXTERNAL_PAYMENT", "WITHDRAWAL", "REFUND", "OTHER"]);

export declare namespace TransactionType {
    export type Raw = "DEPOSIT" | "TRANSFER" | "EXTERNAL_PAYMENT" | "WITHDRAWAL" | "REFUND" | "OTHER";
}
