/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Flagright from "../../api/index";
import * as core from "../../core";
import { TransactionState } from "./TransactionState";
import { TransactionUpdatable } from "./TransactionUpdatable";
import { DeviceData } from "./DeviceData";

export const TransactionEvent: core.serialization.ObjectSchema<
    serializers.TransactionEvent.Raw,
    Flagright.TransactionEvent
> = core.serialization.object({
    transactionState: TransactionState,
    timestamp: core.serialization.number(),
    transactionId: core.serialization.string(),
    eventId: core.serialization.string().optional(),
    reason: core.serialization.string().optional(),
    eventDescription: core.serialization.string().optional(),
    updatedTransactionAttributes: TransactionUpdatable.optional(),
    metaData: DeviceData.optional(),
    updateCount: core.serialization.number().optional(),
});

export declare namespace TransactionEvent {
    export interface Raw {
        transactionState: TransactionState.Raw;
        timestamp: number;
        transactionId: string;
        eventId?: string | null;
        reason?: string | null;
        eventDescription?: string | null;
        updatedTransactionAttributes?: TransactionUpdatable.Raw | null;
        metaData?: DeviceData.Raw | null;
        updateCount?: number | null;
    }
}
