/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Flagright from "../../api/index";
import * as core from "../../core";
import { CardDetails } from "./CardDetails";
import { GenericBankAccountDetails } from "./GenericBankAccountDetails";
import { IbanDetails } from "./IbanDetails";
import { AchDetails } from "./AchDetails";
import { UpiDetails } from "./UpiDetails";
import { WalletDetails } from "./WalletDetails";
import { SwiftDetails } from "./SwiftDetails";
import { MpesaDetails } from "./MpesaDetails";
import { CheckDetails } from "./CheckDetails";
import { CashDetails } from "./CashDetails";

export const TransactionDestinationPaymentDetails: core.serialization.Schema<
    serializers.TransactionDestinationPaymentDetails.Raw,
    Flagright.TransactionDestinationPaymentDetails
> = core.serialization
    .union("method", {
        CARD: CardDetails,
        GENERIC_BANK_ACCOUNT: GenericBankAccountDetails,
        IBAN: IbanDetails,
        ACH: AchDetails,
        UPI: UpiDetails,
        WALLET: WalletDetails,
        SWIFT: SwiftDetails,
        MPESA: MpesaDetails,
        CHECK: CheckDetails,
        CASH: CashDetails,
    })
    .transform<Flagright.TransactionDestinationPaymentDetails>({
        transform: (value) => value,
        untransform: (value) => value,
    });

export declare namespace TransactionDestinationPaymentDetails {
    export type Raw =
        | TransactionDestinationPaymentDetails.Card
        | TransactionDestinationPaymentDetails.GenericBankAccount
        | TransactionDestinationPaymentDetails.Iban
        | TransactionDestinationPaymentDetails.Ach
        | TransactionDestinationPaymentDetails.Upi
        | TransactionDestinationPaymentDetails.Wallet
        | TransactionDestinationPaymentDetails.Swift
        | TransactionDestinationPaymentDetails.Mpesa
        | TransactionDestinationPaymentDetails.Check
        | TransactionDestinationPaymentDetails.Cash;

    export interface Card extends CardDetails.Raw {
        method: "CARD";
    }

    export interface GenericBankAccount extends GenericBankAccountDetails.Raw {
        method: "GENERIC_BANK_ACCOUNT";
    }

    export interface Iban extends IbanDetails.Raw {
        method: "IBAN";
    }

    export interface Ach extends AchDetails.Raw {
        method: "ACH";
    }

    export interface Upi extends UpiDetails.Raw {
        method: "UPI";
    }

    export interface Wallet extends WalletDetails.Raw {
        method: "WALLET";
    }

    export interface Swift extends SwiftDetails.Raw {
        method: "SWIFT";
    }

    export interface Mpesa extends MpesaDetails.Raw {
        method: "MPESA";
    }

    export interface Check extends CheckDetails.Raw {
        method: "CHECK";
    }

    export interface Cash extends CashDetails.Raw {
        method: "CASH";
    }
}
