/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Flagright from "../../api/index";
import * as core from "../../core";
import { BlockchainRisk } from "./BlockchainRisk";

export const TransactionMetadata: core.serialization.ObjectSchema<
    serializers.TransactionMetadata.Raw,
    Flagright.TransactionMetadata
> = core.serialization.object({
    blockchainRisk: core.serialization.list(BlockchainRisk).optional(),
});

export declare namespace TransactionMetadata {
    export interface Raw {
        blockchainRisk?: BlockchainRisk.Raw[] | null;
    }
}
