/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Flagright from "../../api";
import * as core from "../../core";

export const TransactionLimits: core.serialization.ObjectSchema<
    serializers.TransactionLimits.Raw,
    Flagright.TransactionLimits
> = core.serialization.object({
    maximumDailyTransactionLimit: core.serialization.lazyObject(async () => (await import("..")).Amount).optional(),
    maximumWeeklyTransactionLimit: core.serialization.lazyObject(async () => (await import("..")).Amount).optional(),
    maximumMonthlyTransactionLimit: core.serialization.lazyObject(async () => (await import("..")).Amount).optional(),
    maximumQuarterlyTransactionLimit: core.serialization.lazyObject(async () => (await import("..")).Amount).optional(),
    maximumTransactionLimit: core.serialization.lazyObject(async () => (await import("..")).Amount).optional(),
    maximumYearlyTransactionLimit: core.serialization.lazyObject(async () => (await import("..")).Amount).optional(),
    paymentMethodLimits: core.serialization
        .lazyObject(async () => (await import("..")).TransactionLimitsPaymentMethodLimits)
        .optional(),
});

export declare namespace TransactionLimits {
    interface Raw {
        maximumDailyTransactionLimit?: serializers.Amount.Raw | null;
        maximumWeeklyTransactionLimit?: serializers.Amount.Raw | null;
        maximumMonthlyTransactionLimit?: serializers.Amount.Raw | null;
        maximumQuarterlyTransactionLimit?: serializers.Amount.Raw | null;
        maximumTransactionLimit?: serializers.Amount.Raw | null;
        maximumYearlyTransactionLimit?: serializers.Amount.Raw | null;
        paymentMethodLimits?: serializers.TransactionLimitsPaymentMethodLimits.Raw | null;
    }
}
