/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Flagright from "../../api";
import * as core from "../../core";

export const TransactionAmountLimit: core.serialization.ObjectSchema<
    serializers.TransactionAmountLimit.Raw,
    Flagright.TransactionAmountLimit
> = core.serialization.object({
    day: core.serialization.lazyObject(async () => (await import("..")).Amount).optional(),
    week: core.serialization.lazyObject(async () => (await import("..")).Amount).optional(),
    month: core.serialization.lazyObject(async () => (await import("..")).Amount).optional(),
    year: core.serialization.lazyObject(async () => (await import("..")).Amount).optional(),
});

export declare namespace TransactionAmountLimit {
    interface Raw {
        day?: serializers.Amount.Raw | null;
        week?: serializers.Amount.Raw | null;
        month?: serializers.Amount.Raw | null;
        year?: serializers.Amount.Raw | null;
    }
}
