/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Flagright from "../../api";
import * as core from "../../core";

export const TransactionWithRulesResult: core.serialization.ObjectSchema<
    serializers.TransactionWithRulesResult.Raw,
    Flagright.TransactionWithRulesResult
> = core.serialization
    .object({
        executedRules: core.serialization.list(
            core.serialization.lazyObject(async () => (await import("..")).ExecutedRulesResult)
        ),
        hitRules: core.serialization.list(
            core.serialization.lazyObject(async () => (await import("..")).HitRulesDetails)
        ),
    })
    .extend(core.serialization.lazyObject(async () => (await import("..")).Transaction));

export declare namespace TransactionWithRulesResult {
    interface Raw extends serializers.Transaction.Raw {
        executedRules: serializers.ExecutedRulesResult.Raw[];
        hitRules: serializers.HitRulesDetails.Raw[];
    }
}
