/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Flagright from "../../api/index";
import * as core from "../../core";
import { Address } from "./Address";
import { EmailId } from "./EmailId";
import { Tag } from "./Tag";

export const UpiDetails: core.serialization.ObjectSchema<serializers.UpiDetails.Raw, Flagright.UpiDetails> =
    core.serialization.object({
        upiId: core.serialization.property("upiID", core.serialization.string()),
        bankProvider: core.serialization.string().optional(),
        interfaceProvider: core.serialization.string().optional(),
        name: core.serialization.string().optional(),
        address: Address.optional(),
        emailId: EmailId.optional(),
        tags: core.serialization.list(Tag).optional(),
    });

export declare namespace UpiDetails {
    export interface Raw {
        upiID: string;
        bankProvider?: string | null;
        interfaceProvider?: string | null;
        name?: string | null;
        address?: Address.Raw | null;
        emailId?: EmailId.Raw | null;
        tags?: Tag.Raw[] | null;
    }
}
