/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Flagright from "../../api/index";
import * as core from "../../core";

export const UserState: core.serialization.Schema<serializers.UserState.Raw, Flagright.UserState> =
    core.serialization.enum_(["UNACCEPTABLE", "TERMINATED", "ACTIVE", "DORMANT", "CREATED", "SUSPENDED", "BLOCKED"]);

export declare namespace UserState {
    export type Raw = "UNACCEPTABLE" | "TERMINATED" | "ACTIVE" | "DORMANT" | "CREATED" | "SUSPENDED" | "BLOCKED";
}
