/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Flagright from "../../api";
import * as core from "../../core";

export const UserBase: core.serialization.ObjectSchema<serializers.UserBase.Raw, Flagright.UserBase> =
    core.serialization.object({
        userId: core.serialization.string(),
        userDetails: core.serialization.lazyObject(async () => (await import("..")).UserDetails).optional(),
        createdTimestamp: core.serialization.number(),
    });

export declare namespace UserBase {
    interface Raw {
        userId: string;
        userDetails?: serializers.UserDetails.Raw | null;
        createdTimestamp: number;
    }
}
