/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Flagright from "../../api";
import * as core from "../../core";

export const UserWithRulesResultSavedPaymentDetailsItem: core.serialization.Schema<
    serializers.UserWithRulesResultSavedPaymentDetailsItem.Raw,
    Flagright.UserWithRulesResultSavedPaymentDetailsItem
> = core.serialization
    .union("method", {
        CARD: core.serialization.lazyObject(async () => (await import("..")).CardDetails),
        GENERIC_BANK_ACCOUNT: core.serialization.lazyObject(async () => (await import("..")).GenericBankAccountDetails),
        IBAN: core.serialization.lazyObject(async () => (await import("..")).IbanDetails),
        ACH: core.serialization.lazyObject(async () => (await import("..")).AchDetails),
        SWIFT: core.serialization.lazyObject(async () => (await import("..")).SwiftDetails),
        MPESA: core.serialization.lazyObject(async () => (await import("..")).MpesaDetails),
        UPI: core.serialization.lazyObject(async () => (await import("..")).UpiDetails),
        WALLET: core.serialization.lazyObject(async () => (await import("..")).WalletDetails),
        CHECK: core.serialization.lazyObject(async () => (await import("..")).CheckDetails),
        CASH: core.serialization.lazyObject(async () => (await import("..")).CheckDetails),
    })
    .transform<Flagright.UserWithRulesResultSavedPaymentDetailsItem>({
        transform: (value) => value,
        untransform: (value) => value,
    });

export declare namespace UserWithRulesResultSavedPaymentDetailsItem {
    type Raw =
        | UserWithRulesResultSavedPaymentDetailsItem.Card
        | UserWithRulesResultSavedPaymentDetailsItem.GenericBankAccount
        | UserWithRulesResultSavedPaymentDetailsItem.Iban
        | UserWithRulesResultSavedPaymentDetailsItem.Ach
        | UserWithRulesResultSavedPaymentDetailsItem.Swift
        | UserWithRulesResultSavedPaymentDetailsItem.Mpesa
        | UserWithRulesResultSavedPaymentDetailsItem.Upi
        | UserWithRulesResultSavedPaymentDetailsItem.Wallet
        | UserWithRulesResultSavedPaymentDetailsItem.Check
        | UserWithRulesResultSavedPaymentDetailsItem.Cash;

    interface Card extends serializers.CardDetails.Raw {
        method: "CARD";
    }

    interface GenericBankAccount extends serializers.GenericBankAccountDetails.Raw {
        method: "GENERIC_BANK_ACCOUNT";
    }

    interface Iban extends serializers.IbanDetails.Raw {
        method: "IBAN";
    }

    interface Ach extends serializers.AchDetails.Raw {
        method: "ACH";
    }

    interface Swift extends serializers.SwiftDetails.Raw {
        method: "SWIFT";
    }

    interface Mpesa extends serializers.MpesaDetails.Raw {
        method: "MPESA";
    }

    interface Upi extends serializers.UpiDetails.Raw {
        method: "UPI";
    }

    interface Wallet extends serializers.WalletDetails.Raw {
        method: "WALLET";
    }

    interface Check extends serializers.CheckDetails.Raw {
        method: "CHECK";
    }

    interface Cash extends serializers.CheckDetails.Raw {
        method: "CASH";
    }
}
