/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Flagright from "../../api";
import * as core from "../../core";

export const UserDetailsGender: core.serialization.Schema<
    serializers.UserDetailsGender.Raw,
    Flagright.UserDetailsGender
> = core.serialization.enum_(["M", "F", "NB"]);

export declare namespace UserDetailsGender {
    type Raw = "M" | "F" | "NB";
}
