/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Flagright from "../../api";
import * as core from "../../core";

export const UserTag: core.serialization.ObjectSchema<serializers.UserTag.Raw, Flagright.UserTag> =
    core.serialization.object({
        key: core.serialization.string(),
        value: core.serialization.string(),
        isEditable: core.serialization.boolean().optional(),
    });

export declare namespace UserTag {
    interface Raw {
        key: string;
        value: string;
        isEditable?: boolean | null;
    }
}
