/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Flagright from "../../api/index";
import * as core from "../../core";
import { ConsumerName } from "./ConsumerName";
import { CountryCode } from "./CountryCode";
import { Gender } from "./Gender";
import { MaritalStatus } from "./MaritalStatus";
import { PlaceOfBirth } from "./PlaceOfBirth";

export const UserDetails: core.serialization.ObjectSchema<serializers.UserDetails.Raw, Flagright.UserDetails> =
    core.serialization.object({
        name: ConsumerName.optional(),
        dateOfBirth: core.serialization.string().optional(),
        userCategory: core.serialization.string().optional(),
        countryOfResidence: CountryCode.optional(),
        countryOfTaxResidence: CountryCode.optional(),
        countryOfNationality: CountryCode.optional(),
        gender: Gender.optional(),
        maritalStatus: MaritalStatus.optional(),
        placeOfBirth: PlaceOfBirth.optional(),
        alias: core.serialization.list(core.serialization.string()).optional(),
    });

export declare namespace UserDetails {
    export interface Raw {
        name?: ConsumerName.Raw | null;
        dateOfBirth?: string | null;
        userCategory?: string | null;
        countryOfResidence?: CountryCode.Raw | null;
        countryOfTaxResidence?: CountryCode.Raw | null;
        countryOfNationality?: CountryCode.Raw | null;
        gender?: Gender.Raw | null;
        maritalStatus?: MaritalStatus.Raw | null;
        placeOfBirth?: PlaceOfBirth.Raw | null;
        alias?: string[] | null;
    }
}
