/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Flagright from "../../api";
import * as core from "../../core";

export const UserOptionalUserSegment: core.serialization.Schema<
    serializers.UserOptionalUserSegment.Raw,
    Flagright.UserOptionalUserSegment
> = core.serialization.enum_(["RETAIL", "PROFESSIONAL"]);

export declare namespace UserOptionalUserSegment {
    type Raw = "RETAIL" | "PROFESSIONAL";
}
