/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Flagright from "../../api";
import * as core from "../../core";

export const UserStateDetails: core.serialization.ObjectSchema<
    serializers.UserStateDetails.Raw,
    Flagright.UserStateDetails
> = core.serialization.object({
    reason: core.serialization.string().optional(),
    state: core.serialization.lazy(async () => (await import("..")).UserState),
});

export declare namespace UserStateDetails {
    interface Raw {
        reason?: string | null;
        state: serializers.UserState.Raw;
    }
}
