/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Flagright from "../../api/index";
import * as core from "../../core";

export const UserEntityLink: core.serialization.ObjectSchema<serializers.UserEntityLink.Raw, Flagright.UserEntityLink> =
    core.serialization.object({
        parentUserId: core.serialization.string().optional(),
    });

export declare namespace UserEntityLink {
    export interface Raw {
        parentUserId?: string | null;
    }
}
