/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Flagright from "../../api";
import * as core from "../../core";

export const UserRegistrationStatus: core.serialization.Schema<
    serializers.UserRegistrationStatus.Raw,
    Flagright.UserRegistrationStatus
> = core.serialization.enum_(["REGISTERED", "UNREGISTERED"]);

export declare namespace UserRegistrationStatus {
    type Raw = "REGISTERED" | "UNREGISTERED";
}
