/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Flagright from "../../api/index";
import * as core from "../../core";
import { KycStatus } from "./KycStatus";

export const WebhookKycStatusDetails: core.serialization.ObjectSchema<
    serializers.WebhookKycStatusDetails.Raw,
    Flagright.WebhookKycStatusDetails
> = core.serialization.object({
    reason: core.serialization.string().optional(),
    status: KycStatus.optional(),
    userId: core.serialization.string(),
});

export declare namespace WebhookKycStatusDetails {
    export interface Raw {
        reason?: string | null;
        status?: KycStatus.Raw | null;
        userId: string;
    }
}
