/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Flagright from "../../api/index";
import * as core from "../../core";
import { WebhookUserStateDetails } from "./WebhookUserStateDetails";
import { CaseStatusDetails } from "./CaseStatusDetails";
import { CaseOpenedDetails } from "./CaseOpenedDetails";
import { AlertStatusDetails } from "./AlertStatusDetails";
import { AlertOpenedDetails } from "./AlertOpenedDetails";
import { TransactionStatusDetails } from "./TransactionStatusDetails";
import { WebhookKycStatusDetails } from "./WebhookKycStatusDetails";
import { UserTagsUpdate } from "./UserTagsUpdate";
import { CaseTagsUpdate } from "./CaseTagsUpdate";
import { AlertTagsUpdate } from "./AlertTagsUpdate";
import { CraRiskLevelUpdatedDetails } from "./CraRiskLevelUpdatedDetails";
import { BatchCompletedDetails } from "./BatchCompletedDetails";
import { WebhookPepStatusDetails } from "./WebhookPepStatusDetails";
import { WebhookSanctionsStatusDetails } from "./WebhookSanctionsStatusDetails";
import { WebhookAdverseMediaStatusDetails } from "./WebhookAdverseMediaStatusDetails";

export const WebhookEventData: core.serialization.Schema<serializers.WebhookEventData.Raw, Flagright.WebhookEventData> =
    core.serialization.undiscriminatedUnion([
        WebhookUserStateDetails,
        CaseStatusDetails,
        CaseOpenedDetails,
        AlertStatusDetails,
        AlertOpenedDetails,
        TransactionStatusDetails,
        WebhookKycStatusDetails,
        UserTagsUpdate,
        CaseTagsUpdate,
        AlertTagsUpdate,
        CraRiskLevelUpdatedDetails,
        BatchCompletedDetails,
        WebhookPepStatusDetails,
        WebhookSanctionsStatusDetails,
        WebhookAdverseMediaStatusDetails,
    ]);

export declare namespace WebhookEventData {
    export type Raw =
        | WebhookUserStateDetails.Raw
        | CaseStatusDetails.Raw
        | CaseOpenedDetails.Raw
        | AlertStatusDetails.Raw
        | AlertOpenedDetails.Raw
        | TransactionStatusDetails.Raw
        | WebhookKycStatusDetails.Raw
        | UserTagsUpdate.Raw
        | CaseTagsUpdate.Raw
        | AlertTagsUpdate.Raw
        | CraRiskLevelUpdatedDetails.Raw
        | BatchCompletedDetails.Raw
        | WebhookPepStatusDetails.Raw
        | WebhookSanctionsStatusDetails.Raw
        | WebhookAdverseMediaStatusDetails.Raw;
}
