/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../..";
import * as Flagright from "../../../../../api";
import * as core from "../../../../../core";

export const BusinessUserEventBatchRequest: core.serialization.Schema<
    serializers.BusinessUserEventBatchRequest.Raw,
    Flagright.BusinessUserEventBatchRequest
> = core.serialization.object({
    batchId: core.serialization.string().optional(),
    data: core.serialization.list(
        core.serialization.lazyObject(async () => (await import("../../../..")).BusinessUserEvent)
    ),
});

export declare namespace BusinessUserEventBatchRequest {
    interface Raw {
        batchId?: string | null;
        data: serializers.BusinessUserEvent.Raw[];
    }
}
