/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Flagright from "../../../../api/index";
import * as core from "../../../../core";
import { UserWithRulesResult } from "../../../types/UserWithRulesResult";

export const ConsumerUserEventsCreateResponse: core.serialization.ObjectSchema<
    serializers.ConsumerUserEventsCreateResponse.Raw,
    Flagright.ConsumerUserEventsCreateResponse
> = core.serialization
    .object({
        message: core.serialization.string().optional(),
    })
    .extend(UserWithRulesResult);

export declare namespace ConsumerUserEventsCreateResponse {
    export interface Raw extends UserWithRulesResult.Raw {
        message?: string | null;
    }
}
