/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "./environments";
import * as core from "./core";
import { Transactions } from "./api/resources/transactions/client/Client";
import { TransactionEvents } from "./api/resources/transactionEvents/client/Client";
import { ConsumerUsers } from "./api/resources/consumerUsers/client/Client";
import { BusinessUsers } from "./api/resources/businessUsers/client/Client";
import { ConsumerUserEvents } from "./api/resources/consumerUserEvents/client/Client";
import { BusinessUserEvents } from "./api/resources/businessUserEvents/client/Client";

export declare namespace FlagrightClient {
    interface Options {
        environment?: core.Supplier<environments.FlagrightEnvironment | string>;
        apiKey: core.Supplier<string>;
    }

    interface RequestOptions {
        timeoutInSeconds?: number;
        maxRetries?: number;
    }
}

export class FlagrightClient {
    constructor(protected readonly _options: FlagrightClient.Options) {}

    protected _transactions: Transactions | undefined;

    public get transactions(): Transactions {
        return (this._transactions ??= new Transactions(this._options));
    }

    protected _transactionEvents: TransactionEvents | undefined;

    public get transactionEvents(): TransactionEvents {
        return (this._transactionEvents ??= new TransactionEvents(this._options));
    }

    protected _consumerUsers: ConsumerUsers | undefined;

    public get consumerUsers(): ConsumerUsers {
        return (this._consumerUsers ??= new ConsumerUsers(this._options));
    }

    protected _businessUsers: BusinessUsers | undefined;

    public get businessUsers(): BusinessUsers {
        return (this._businessUsers ??= new BusinessUsers(this._options));
    }

    protected _consumerUserEvents: ConsumerUserEvents | undefined;

    public get consumerUserEvents(): ConsumerUserEvents {
        return (this._consumerUserEvents ??= new ConsumerUserEvents(this._options));
    }

    protected _businessUserEvents: BusinessUserEvents | undefined;

    public get businessUserEvents(): BusinessUserEvents {
        return (this._businessUserEvents ??= new BusinessUserEvents(this._options));
    }
}
