/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const FlagrightEnvironment = {
    Sandbox: "https://sandbox.api.flagright.com",
    Production: "https://api.flagright.com",
} as const;

export type FlagrightEnvironment = typeof FlagrightEnvironment.Sandbox | typeof FlagrightEnvironment.Production;
