/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const FlagrightApiEnvironment = {
    Production: "https://api.flagright.com",
    Sandbox: "https://sandbox.api.flagright.com",
} as const;

export type FlagrightApiEnvironment =
    | typeof FlagrightApiEnvironment.Production
    | typeof FlagrightApiEnvironment.Sandbox;
